#!/usr/bin/env python3
"""Natural-phrases N3 (docs/natural-phrases-plan.md N3): regenerate
../assets/eng/templates.toml from the GF sources in this directory (Gloss.gf, GlossFunctor.gf,
GlossEng.gf, LexGloss.gf, LexGlossEng.gf).

NOT CI-verified: there is no `gf` install on this machine as of 2026-07-11, so this script has
never actually been run end to end. Its logic (the `gf --make` / `gf --run` invocation shapes,
and the exact stdout format `gf --run` produces for a batch of piped `linearize` commands) was
written from documented GF CLI behavior, not confirmed by execution -- inspect the raw output
this script prints on any failure and adjust `run_gf_shell` below before trusting it. Only
Python's standard library is used (no new dependency, matching the workspace's zero-external-dep
posture -- docs/natural-phrases-plan.md's non-negotiable constraint 3, which this crate's Rust
side also honors).

Exact invocation once a working `gf` install exists:

    python gen_templates.py --gf gf --out ../assets/eng/templates.toml

(run from this directory; `--gf` defaults to "gf" already on PATH, `--out` defaults to the path
above, so a bare `python gen_templates.py` does the same thing).

What it does:
  1. `gf --make --output-format=pgf GlossEng.gf` -- compiles the functor instantiation (and
     everything it depends on) to Gloss.pgf (named after the abstract module, Gloss.gf).
  2. Builds the 4 (Case) x 9 (Poss) x 3 (GNum) = 108 abstract trees, one per construction cell,
     in the same nested order as rust/crates/pg-realize/src/ir.rs's CaseRole::ALL / Poss::ALL /
     Num::ALL declaration order -- the order the committed templates.toml is itself sorted in.
  3. Feeds all 108 `linearize <tree>` commands to `gf --run Gloss.pgf` in one batch (one process,
     not 108) and reads back one output line per command.
  4. Substitutes the placeholder word ("house"/"houses", from LexGlossEng.gf's `n_N = mkN
     "house"`) back out for the real `{n:sg}`/`{n:pl}` slot templates.toml's Rust reader
     (rust/crates/pg-realize/src/table.rs's `load_cells`) expects -- erroring out if a
     linearization does not contain the expected placeholder form exactly once (the substitution
     invariant table.rs's own load-time validation also checks on the Rust side).
  5. Rewrites templates.toml with the same header comment shape and `[cells]` key format as the
     currently-committed, hand-authored file, so a diff against the previous commit is a pure
     content diff, not a format churn.
"""

import argparse
import pathlib
import re
import subprocess
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
ABSTRACT_MODULE_GF = "GlossEng.gf"
PGF_NAME = "Gloss.pgf"  # `gf --make` names the .pgf after the abstract module (Gloss.gf -> Gloss.pgf).

# (TOML key component, GF abstract fun name) -- mirrors ir.rs's CaseRole::ALL declaration order.
CASES = [
    ("None", "NoCase"),
    ("Loc", "LocCase"),
    ("Abl", "AblCase"),
    ("All", "AllCase"),
]

# Mirrors ir.rs's Poss::ALL declaration order. Every fun name equals its TOML key component
# except None/NoPoss.
POSSES = [
    ("None", "NoPoss"),
    ("P1Sg", "P1Sg"),
    ("P1Pl", "P1Pl"),
    ("P2SgM", "P2SgM"),
    ("P2SgF", "P2SgF"),
    ("P2Pl", "P2Pl"),
    ("P3SgM", "P3SgM"),
    ("P3SgF", "P3SgF"),
    ("P3Pl", "P3Pl"),
]

# Mirrors ir.rs's Num::ALL declaration order.
NUMS = [
    ("Unspec", "NumUnspec"),
    ("Sg", "NumSg"),
    ("Pl", "NumPl"),
]

PLACEHOLDER_SG = "house"
PLACEHOLDER_PL = "houses"

HEADER = """# Natural-phrases N3 (docs/natural-phrases-plan.md N3) English construction-cell table for
# pg_realize::table::TableRealizer, loaded via include_str!.
#
# GENERATED by gf/gen_templates.py from the GF sources in rust/crates/pg-realize/gf/ (Gloss.gf,
# GlossFunctor.gf, GlossEng.gf, LexGloss.gf, LexGlossEng.gf) -- do not hand-edit; edit the .gf
# sources and re-run `python gen_templates.py --gf gf --out ../assets/eng/templates.toml` from
# that directory instead. See rust/crates/pg-realize/README.md for the full regeneration loop.
#
# One entry per (CaseRole, Poss, Num) cell -- key = "Case.Poss.Num" (dotted, hence quoted --
# pg_realize::map's restricted-TOML-subset key rule requires quoting for keys with characters
# other than letters/digits/'_'/'-'). Value is an English template with exactly one `{n:sg}` or
# `{n:pl}` slot -- pg_realize::table::TableRealizer fills that slot with the concept's singular
# or plural noun form and leaves the rest of the template text verbatim.
"""


class GenError(RuntimeError):
    """A regeneration failure -- always printed with a `gen_templates.py:` prefix, never a raw
    traceback, since every failure mode here is meant to be an actionable message about GF's
    actual behavior once someone has a working `gf` install to debug against."""


def compile_grammar(gf_bin: str, workdir: pathlib.Path) -> pathlib.Path:
    cmd = [gf_bin, "--make", "--output-format=pgf", ABSTRACT_MODULE_GF]
    proc = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True)
    if proc.returncode != 0:
        raise GenError(
            f"`{' '.join(cmd)}` failed (exit {proc.returncode}):\n{proc.stdout}\n{proc.stderr}"
        )
    pgf_path = workdir / PGF_NAME
    if not pgf_path.exists():
        raise GenError(
            f"expected {pgf_path} after `gf --make` but it was not created -- gf's actual output "
            f"filename may differ from what this script assumes; check the `gf --make` stdout "
            f"above and adjust PGF_NAME."
        )
    return pgf_path


def build_cells() -> list:
    """Return one (toml_key, gf_tree, is_plural) tuple per construction cell, in the exact order
    the committed templates.toml is sorted in (CaseRole outer, Poss middle, Num inner -- mirrors
    ir.rs's CaseRole::ALL / Poss::ALL / Num::ALL declaration order)."""
    cells = []
    for case_key, case_fun in CASES:
        for poss_key, poss_fun in POSSES:
            for num_key, num_fun in NUMS:
                toml_key = f"{case_key}.{poss_key}.{num_key}"
                tree = f"GlossPhrase {case_fun} {poss_fun} {num_fun} n_N"
                cells.append((toml_key, tree, num_key == "Pl"))
    return cells


def run_gf_shell(gf_bin: str, pgf_path: pathlib.Path, trees) -> list:
    """Feed one `linearize <tree>` command per tree to `gf --run <pgf>` in a single batch and
    return the output lines, one per command, in order.

    NOT CI-verified (see module docstring): this assumes `gf --run` reading a script from stdin
    prints exactly one non-empty output line per `linearize` command, with no extra banner/prompt
    lines mixed in -- documented GF shell batch behavior, not confirmed by execution here. If the
    real output includes banner lines or per-command echoing, the line-count check below will
    fail loudly (rather than silently misaligning commands with results) and the raw stdout is
    included in the error so this function's parsing can be corrected.
    """
    script = "\n".join(f"linearize {tree}" for _, tree, _ in trees) + "\n"
    cmd = [gf_bin, "--run", str(pgf_path)]
    proc = subprocess.run(cmd, input=script, capture_output=True, text=True)
    if proc.returncode != 0:
        raise GenError(
            f"`{' '.join(cmd)}` failed (exit {proc.returncode}):\n{proc.stdout}\n{proc.stderr}"
        )
    lines = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
    if len(lines) != len(trees):
        raise GenError(
            f"gf --run produced {len(lines)} non-empty output lines for {len(trees)} "
            f"`linearize` commands -- this script's assumption about gf --run's batch output "
            f"format (module docstring) does not hold; raw stdout follows so run_gf_shell can be "
            f"fixed:\n{proc.stdout}"
        )
    return lines


def substitute_placeholder(text: str, is_plural: bool) -> str:
    """Replace the one expected occurrence of the placeholder word ("house" or "houses",
    matching `is_plural`) with the `{n:sg}`/`{n:pl}` slot templates.toml's Rust reader expects.
    Errors out (the task's explicit substitution-invariant requirement) if the expected
    placeholder form is not present in `text` exactly once."""
    placeholder = PLACEHOLDER_PL if is_plural else PLACEHOLDER_SG
    slot = "{n:pl}" if is_plural else "{n:sg}"
    matches = list(re.finditer(rf"\b{re.escape(placeholder)}\b", text))
    if len(matches) != 1:
        raise GenError(
            f"linearization {text!r} contains the placeholder {placeholder!r} "
            f"{len(matches)} time(s), expected exactly 1 -- substitution invariant violated "
            f"(check LexGlossEng.gf's n_N and GlossFunctor.gf's construction for this cell)"
        )
    m = matches[0]
    return text[: m.start()] + slot + text[m.end() :]


def render_toml(cells) -> str:
    lines = [HEADER, "[cells]", ""]
    last_case = None
    for toml_key, value in cells:
        case = toml_key.split(".", 1)[0]
        if case != last_case:
            if last_case is not None:
                lines.append("")
            lines.append(
                f"# --- CaseRole::{case} "
                + "-" * (75 - len(f"# --- CaseRole::{case} "))
            )
            last_case = case
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'"{toml_key}" = "{escaped}"')
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--gf", default="gf", help="path to the gf executable (default: gf on PATH)")
    parser.add_argument(
        "--out",
        default="../assets/eng/templates.toml",
        help="output path, relative to this script's directory unless absolute "
        "(default: ../assets/eng/templates.toml)",
    )
    args = parser.parse_args()

    out_path = pathlib.Path(args.out)
    if not out_path.is_absolute():
        out_path = (SCRIPT_DIR / out_path).resolve()

    pgf_path = compile_grammar(args.gf, SCRIPT_DIR)
    cells = build_cells()
    raw_lines = run_gf_shell(args.gf, pgf_path, cells)

    substituted = []
    for (toml_key, _tree, is_plural), raw in zip(cells, raw_lines):
        substituted.append((toml_key, substitute_placeholder(raw, is_plural)))

    out_path.write_text(render_toml(substituted), encoding="utf-8", newline="\n")
    print(f"wrote {len(substituted)} cells to {out_path}")


if __name__ == "__main__":
    try:
        main()
    except GenError as e:
        print(f"gen_templates.py: {e}", file=sys.stderr)
        sys.exit(1)
