[package]
name = "hc-hybrid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hc-grammar.workspace = true
hc-featstruct.workspace = true
hc-shape.workspace = true
hc-rules.workspace = true
hc-parse.workspace = true
rustc-hash.workspace = true
unicode-normalization.workspace = true
rayon.workspace = true
