//! The conformance-coverage cross-check, shipped
//! here as a **NON-BLOCKING, advisory preview** — the same non-blocking-first pattern
//! `crate::capability`'s own `characterize` (computes only) → `compose_envelope` (CHECK-ONLY) →
//! a later, deliberate compile-blocking step already used.
//!
//! This crate's own honest-capability discipline: "'Supported' is mechanically gated on passing conformance coverage... CI
//! cross-checks the capability registry (the source-controlled, per-construct
//! supported/unsupported contract)... against conformance coverage (`constructs.txt` / per-word
//! `exercises:` / `rules.csv`), and marking anything supported without a covering, passing fixture
//! **breaks the build**." This module supplies the mapping (deliverable 1) and the pure
//! cross-check function (deliverable 2) that claim answers; **nothing in this crate or its test
//! suite yet enforces `gaps.is_empty()`** — see "End state" below.
//!
//! # The two sides of the cross-check
//! - **The registry side**: `crate::capability::CharacteristicKind` + [`crate::capability::
//!   CharacteristicKind::default_disposition`] — `Disposition::Proven` is today's actual
//!   "supported (admission-proven)" set; `ConfirmOnly`/`ConfigPredicate`
//!   are compiled-or-relied-upon capabilities in their own right, just not
//!   admission-proven — see "The cross-check is ledger-wide" below for why this module
//!   reasons about every disposition, not `Proven` alone.
//! - **The coverage side**: `machine/conformance/constructs.txt`'s flat checklist of construct
//!   identifiers, which every fixture's `words.yaml` `exercises:` entries (per-word AND per-parse,
//!   `pg_conformance_fixtures::{WordEntry, ParseEntry}`) are supposed to draw verbatim from
//!   (`constructs.txt`'s own header comment). `coverage.csv`/`rules.csv` are the C# oracle's own
//!   GENERATED cross-reference of the same data — this module does not read those two files
//!   directly (they are regenerated by `dotnet run ... --coverage-report`, a tool this Rust
//!   workspace does not invoke), it re-derives the same "which construct ids are exercised"
//!   question straight from `words.yaml`, which is the actual committed ground truth.
//!
//! # The cross-check is ledger-wide
//! `supported_kinds` returns every `CharacteristicKind` ([`crate::capability::
//! CharacteristicKind::ALL`]), not just the `Disposition::Proven` subset. Scoping it to `Proven`
//! made the cross-check vacuous for most of the ledger — the majority of rows were never asked
//! about at all. Every disposition here is a compiled-or-relied-upon capability, so every row
//! needs the same evidence: a covering, PASSING analysis fixture.
//! `CoverageReportRow::disposition` is carried on the row itself so a build-breaking flip can
//! stage `Proven` ahead of `ConfigPredicate`/`ConfirmOnly` without re-deriving the report.
//!
//! # What "passing" means here (a judgment call, flagged)
//! This crate's honest-capability discipline says a construct needs "a covering, **passing** fixture" — not merely a fixture that
//! *mentions* the construct in an `exercises:` tag. This module itself takes no position on how
//! "passing" is established (it is a pure function over a caller-supplied
//! `passing_covered_constructs: &HashSet<&str>>`), so the actual engine-replay work stays a
//! dev-dependency-only concern: `tests/conformance_coverage_gate.rs` (this crate) builds that set
//! by replaying every discovered fixture (`pg_conformance_fixtures::discover`) against
//! `pg_parse::Morpher` — the SAME oracle `pg-parse`'s own `conformance_fixtures_gate.rs` already
//! runs the full suite against — and only credits a word's/parse's `exercises:` tags toward
//! coverage when that word's engine output actually matches the fixture's declared ground truth
//! signature. A currently-*failing* word's `exercises:` tags do not count.
//!
//! # The mapping (deliverable 1 — THE CONTRACT)
//! `construct_ids_for` is hand-authored and exhaustively matched (no catch-all arm — adding a
//! `CharacteristicKind` variant breaks this file's build, same discipline `characterize`/
//! `default_disposition` already hold themselves to). Before G9, three kinds returned an **empty slice** —
//! `CharacteristicKind::LeftToRightRewrite`, `CharacteristicKind::RightToLeftRewrite`, and
//! `CharacteristicKind::SubruleGating` (`CharacteristicKind::MultiTable` was the fourth,
//! already documented separately below) — because `constructs.txt` had no row distinguishing
//! rewrite direction or subrule-level MPR/POS gating as its own tagged phenomenon. G9 added the
//! four missing rows upstream and this function now maps all four; see `construct_ids_for`'s own
//! per-arm doc for exactly which row each maps to and why the old mapping was genuinely absent
//! rather than mismapped. `ORPHAN_CONSTRUCT_ROWS` is the mirror-image list this same audit
//! surfaced — 12 `constructs.txt` rows with NO corresponding `CharacteristicKind`, deliberately
//! left unmapped (not invented) with a documented reason each.
//! `CoverageStatus::Unmappable` surfaces a construct-id-less kind separately from
//! `CoverageStatus::Uncovered` (a real construct id exists, but the required evidence is
//! missing) so a reader never conflates "nobody has produced the evidence yet" with "there is
//! nothing to produce evidence FOR." After G9, zero kinds are `Unmappable` (see
//! `zero_unmappable_after_g9`).
//!
//! # Investigation finding: does `words.yaml` cleanly support "construct X is exercised by a
//! passing fixture"?
//! **Yes, with one caveat.** `exercises:` is a first-class, already-populated field on both
//! `WordEntry` and `ParseEntry` (`pg_conformance_fixtures::{WordEntry, ParseEntry}`), populated
//! from `constructs.txt`'s verbatim identifiers today (`coverage.csv` proves this: every
//! `construct` column value there is a literal `constructs.txt` line). So the coverage metadata
//! does NOT need new fixture tagging to answer "is construct X exercised anywhere" — that much is
//! already clean. The caveat is "passing": `exercises:` tags a word/parse with a construct
//! regardless of whether any given ENGINE currently gets that word right — the tag is
//! ground-truth metadata about the FIXTURE, not a per-engine pass/fail record. Answering "passing"
//! therefore requires actually replaying the fixture (this crate's test does exactly that against
//! `pg_parse::Morpher`), rather than reading a static column — a real, if modest, gap between what
//! `words.yaml` states and what this cross-check needs, closed here by re-deriving pass/fail via
//! replay rather than by asking for new fixture tagging.
//!
//! # End state
//! A hard CI gate asserts `supported_uncovered(&covered).is_empty()` in
//! `tests/conformance_coverage_gate.rs`. A staged flip is still available if gaps reappear:
//! `Proven` rows are a hard error ahead of `ConfigPredicate`/`ConfirmOnly` rows, distinguishable
//! via `disposition`.
//!
//! # The structural-witness gate: closing the last silent-inheritance hole before a flip
//! `construct_ids_for` maps some `constructs.txt` row ids from MORE THAN ONE `CharacteristicKind`
//! (a coarser characteristic and a finer one genuinely sharing the same upstream row — `constructs.
//! txt` has no finer-grained id for either). That is fine for the coarser kind, but it means the
//! finer kind's `Covered` status is, MECHANICALLY, satisfied by ANY passing fixture tagging that id
//! — including one that only ever exercised the coarser sibling. `supported_coverage_report`
//! cannot tell "this fixture genuinely exercises the finer construct" from "this fixture exercises
//! the coarser one and happens to share the finer one's row id" — both look identical to a plain
//! set-membership check over `exercises:` tags. A row can therefore report `Covered` forever even if
//! the ONE fixture that ever genuinely exercised the finer construct is deleted, so long as some
//! other, coarser-only fixture keeps tagging the shared id. That silent-rot risk is exactly what
//! makes flipping this cross-check to build-breaking on faith irresponsible.
//!
//! `shared_construct_ids` computes every such shared id directly from `construct_ids_for` (never
//! hardcoded — a future mapping edit is picked up automatically). Every sharing kind is graded
//! against the passing-fixture set, so every shared id is at risk of this inheritance.
//!
//! `registered_structural_witnesses` pairs each at-risk id with a
//! `StructuralWitness`: a predicate over the LOADED `pg_grammar::model::Grammar` (never a second
//! hand-rolled definition of the construct, never a regex over the source XML) that decides whether
//! a grammar structurally exhibits the FINER characteristic — independent of whatever `exercises:`
//! tag a fixture happens to carry. `tests/structural_witness_gate.rs` (this crate) is what actually
//! RUNS these predicates against every discovered, PASSING fixture and asserts each one is satisfied
//! by at least one fixture that *also* tags the shared id on a passing word/parse — pinning the
//! finer characteristic's evidence mechanically rather than leaving it to only ever have been
//! verified by hand. `every_shared_id_has_a_registered_structural_witness` (below,
//! this module) is the generic, string-driven half that needs no fixture I/O at all: it fails loudly
//! if `construct_ids_for` ever grows a NEW shared id with no registered witness, so this
//! protection cannot be silently defeated by a future mapping edit the way the original four ids
//! went unnoticed.

use std::collections::HashSet;

use crate::capability::{CharacteristicKind, Disposition};
use pg_grammar::model::{Grammar, MorphRuleOrder, MprGroupOutput, PhonRuleDef};

/// Deliverable 1, THE CONTRACT: `kind`'s corresponding `machine/conformance/constructs.txt`
/// identifier(s), verbatim (byte-for-byte matching what a `words.yaml` `exercises:` entry would
/// carry — see `constructs.txt`'s own header: "A line's text (verbatim, including punctuation) is
/// the key"). Exhaustively matched (no catch-all): adding a `CharacteristicKind` variant without
/// adding an arm here breaks this crate's build, same discipline
/// `CharacteristicKind::default_disposition` already holds itself to.
///
/// An empty slice is a deliberate, documented "no corresponding coverage identifier exists" —
/// `CoverageStatus::Unmappable`'s trigger, not an oversight:
/// - `CharacteristicKind::MultiTable`: `constructs.txt` has no row tagging "more than one
///   `CharacterDefinitionTable`, each stratum's own" as its own phenomenon — see this function's
///   own match arm for the two near-miss rows considered and rejected.
/// - `CharacteristicKind::LeftToRightRewrite` / `CharacteristicKind::RightToLeftRewrite`:
///   `constructs.txt`'s `RewriteRule Iterative (...)`/`RewriteRule Simultaneous` rows tag
///   *multiple-application order*, not *directionality* — no row anywhere names "left-to-right" or
///   "right-to-left" as its own tagged phenomenon, so no fixture author has anything to write in
///   an `exercises:` list for direction specifically, however many `Dir::RightToLeft` rules a
///   grammar has.
/// - `CharacteristicKind::SubruleGating`: this characteristic is triggered by a
///   `RewriteSubruleDef` declaring `required_pos`/`required_mpr`/`excluded_mpr` — a *phonological*
///   subrule's own MPR/POS gate. `constructs.txt`'s `MPR features/groups` row is the closest
///   textual match, but every `coverage.csv` row actually tagged with it exercises a
///   *morphological* `MprGroup` (`MprGroupAppend`/`MprGroupOverwrite`'s own territory — e.g.
///   Velamba's `mrExtX`/`mrEndW`), never a gated phonological subrule; mapping `SubruleGating` onto
///   that row would overclaim coverage that was never actually exercised for THIS characteristic.
///   No row distinctly tags phonological-subrule-level gating today.
///
/// One further judgment call, NOT an empty mapping: `constructs.txt`'s `"AffixProcessRule:
/// subtraction/truncation"` row is folded into `CharacteristicKind::Affixation`'s mapping rather
/// than given its own `CharacteristicKind`. D1's characterizer (`capability.rs`) has no distinct
/// characteristic for plain (single-part-LHS) truncation — [`CharacteristicKind::
/// CircumfixOutputAction`]'s own trigger (`allomorph_drops_lhs_material`) explicitly early-returns
/// `false` for `lhs.len() <= 1`, so an ordinary subtractive/truncating affix characterizes as
/// plain `Affixation` (Proven), same as any other `AffixProcessRule`. This is not this module
/// inventing a characteristic — it is documenting where `capability.rs`'s own granularity already
/// lands truncation, so the mapping is honest about what `Affixation`'s `Proven` disposition is
/// actually claiming to cover.
///
/// # G9 update
/// The four characteristics that used to return an empty slice here — [`CharacteristicKind::
/// LeftToRightRewrite`], `CharacteristicKind::RightToLeftRewrite`, [`CharacteristicKind::
/// SubruleGating`], `CharacteristicKind::MultiTable` — now map to four NEW `constructs.txt`
/// rows added upstream specifically to close this gap (this function's own previous doc explained
/// exactly why each was a genuine, deliberate non-mapping; that reasoning is preserved below per
/// arm, now paired with the row that was added to resolve it). No other characteristic's mapping
/// changed. `CharacteristicKind::MultiTable` is exhaustively re-verified as the true empty-
/// mapping was NOT a permanent property — see `supported_uncovered` for which rows (mapped or
/// not) still lack a *passing* fixture even after this mapping fix.
pub fn construct_ids_for(kind: CharacteristicKind) -> &'static [&'static str] {
    use CharacteristicKind::*;
    match kind {
        Affixation => &[
            "AffixProcessRule: prefix/suffix/circumfix/infix",
            "AffixProcessRule: subtraction/truncation",
        ],
        RealizationalMorphology => &["RealizationalAffixProcessRule"],
        Compounding => &["CompoundingRule"],
        OrderedMorphRuleApplication => &["Stratum (Linear/Unordered rule order)"],
        UnorderedMorphRuleApplication => &["Stratum (Linear/Unordered rule order)"],
        MprGroupAppend => &["MPR features/groups"],
        MprGroupOverwrite => &["MPR features/groups"],
        IterativeRewrite => {
            &["RewriteRule Iterative (epenthesis/deletion/feature/expansion/merge)"]
        }
        SimultaneousRewrite => &["RewriteRule Simultaneous"],
        // G9: no pre-existing row named rewrite direction as its own phenomenon (the Iterative/Simultaneous rows tag application order, not directionality), so this pair was added upstream.
        LeftToRightRewrite => &["RewriteRule direction (Dir): left-to-right"],
        RightToLeftRewrite => &["RewriteRule direction (Dir): right-to-left"],
        Metathesis => &["MetathesisRule"],
        Epenthesis => &["RewriteRule Iterative (epenthesis/deletion/feature/expansion/merge)"],
        // G9: a phonological subrule's own POS/MPR gate is distinct from MprGroupAppend/Overwrite's morphological MprGroup territory, so no pre-G9 row covered it; added upstream instead of overclaiming the closest-match row.
        SubruleGating => {
            &["RewriteSubruleDef gating: required/excluded POS or MPR at the subrule level"]
        }
        CircumfixOutputAction => &["AffixProcessRule: prefix/suffix/circumfix/infix"],
        Reduplication => &["AffixProcessRule: reduplication (ReduplicationHint)"],
        CoOccurrenceConstraint => &["MorphemeCoOccurrenceRule/AllomorphCoOccurrenceRule"],
        NaturalClassDefinition => {
            &["NaturalClass: Segments vs FeatureNaturalClass/SegmentNaturalClass precision"]
        }
        // G9: the two pre-existing rows mentioning CharacterDefinitionTable are about constructs within one table, not multi-table stratification, so this pair was added upstream.
        MultiTable => &["CharacterDefinitionTable: more than one table, one per stratum"],
        // Unlike MultiTable/LeftToRightRewrite above, "optional group / Kleene star" already had a distinctly-tagged coverage identifier before G9.
        QuantifierPattern => {
            &["CharacterDefinitionTable pattern shapes: optional group / Kleene star"]
        }
        // Removed from ORPHAN_CONSTRUCT_ROWS below now that CharacteristicKind::StemName exists for it (see that type's own doc).
        StemName => &["Stem names"],
        // Same correction, same source row: also used to be in ORPHAN_CONSTRUCT_ROWS.
        FreeFluctuation => &["Disjunctive allomorphs / free-fluctuation"],
    }
}

/// The `constructs.txt` rows that name a genuine construct with NO corresponding
/// `CharacteristicKind` at all (the mirror image of the empty-slice arms `construct_ids_for`
/// used to have before G9 — there, a characteristic existed with no row; here, a row exists with
/// no characteristic). This crate's own discipline: **do not invent characteristics for
/// these** — some are genuinely not compiler/FST-capability concerns at all. This function exists
/// purely as living documentation (nothing calls it at runtime; no test asserts these ARE the only
/// entries — that would require parsing `constructs.txt` at build time, which this crate
/// deliberately does not do, per `construct_ids_for`'s own "hand-authored, verbatim" contract) —
/// see each tuple's second field for why no `CharacteristicKind` was added for it.
///
/// **Correction:** "Stem names" and "Disjunctive allomorphs /
/// free-fluctuation" used to be listed here. Both were wrong: each names a real, separate
/// `model.rs` construct site (`RootAllomorphDef::stem_name`, model.rs:798; the multi-allomorph
/// entry shape the disjunctive re-check engages, `LexEntryDef::allomorphs`, model.rs:777)
/// this crate's capability ledger had simply never recorded at all — not, as the removed entries
/// claimed, ordinary bookkeeping already folded into another characteristic. Both now have their
/// own `CharacteristicKind` (`StemName`/`FreeFluctuation`, both `ConfirmOnly`) and a real
/// `construct_ids_for` mapping above. This does not retract the reasoning for the OTHER entries
/// still listed below (e.g. `MorphRuleDef::required_stem_name`, folded into `Affixation`/
/// `RealizationalMorphology` for a real, still-valid double-counting reason — see
/// `CharacteristicKind::StemName`'s own doc for the distinction).
pub const ORPHAN_CONSTRUCT_ROWS: &[(&str, &str)] = &[
    (
        "MorphologicalOutputAction: CopyFromInput/InsertSegments",
        "an ordinary output-action primitive already exercised as part of Affixation/\
         CircumfixOutputAction coverage; D1's table has no distinct admission-gated characteristic \
         for individual OutputAction variants (they collapse into whichever MorphRuleDef/\
         AffixAllomorphDef characteristic uses them).",
    ),
    (
        "MorphologicalOutputAction: ModifyFromInput/InsertSimpleContext",
        "same reasoning as \"CopyFromInput/InsertSegments\" above -- an ordinary output-action \
         primitive, not its own gated phenomenon.",
    ),
    (
        "Affix template slots (obligatory/disjunctive/ordering)",
        "a morphotactic templating detail already covered generically by Affixation/\
         OrderedMorphRuleApplication proposing; no distinct CharacteristicKind carves out \
         slot-level obligatoriness/ordering as its own admission-filtered phenomenon.",
    ),
    (
        "Boundary markers (CharacterDefinitionTable)",
        "segmentation/tokenization detail within one CharacterDefinitionTable -- purely \
         representational (how raw input is chunked into segments), not itself a proposer/confirm \
         capability axis D1's table gates on (same standing as NaturalClassDefinition's own \
         \"representational only, no capability implication either way\" framing, just not given \
         its own variant).",
    ),
    (
        "Guesser/LexicalGuess",
        "a runtime unknown-word heuristic (HC's guesser subsystem), not a compiled-FST capability; \
         no model.rs construct this crate's characterize() walks corresponds to it at all -- \
         outside this crate's characterization scope entirely.",
    ),
    (
        "Syntactic feature agreement (RequiredHeadFeatures/OutputHeadFeatures/RequiredFootFeatures/\
         OutputFootFeatures)",
        "ordinary confirm-time feature-unification, already assumed faithful per \
         IMPLEMENTATION-READINESS.md R1 (\"HermitCrab and the Rust model are assumed complete \
         apart from bug fixes\"); not a distinct FST-compilation capability axis this crate \
         characterizes.",
    ),
    (
        "Alpha-variable phonological environments (VariableFeature/AlphaVariables)",
        "alpha-variable (feature-agreement) environment matching is a rewrite-rule environment \
         detail, already covered generically by IterativeRewrite/SimultaneousRewrite fixtures; no \
         distinct CharacteristicKind carves out alpha-variable binding as its own admission-gated \
         phenomenon.",
    ),
    (
        "CompoundingRule constraints (MaxApplicationCount/Blockable/head-nonhead syntactic \
         features)",
        "a more granular constraint-configuration variant of CharacteristicKind::Compounding's own \
         construct (the plain \"CompoundingRule\" row); CompoundingRecursionSafePredicate's \
         admit/confirm/refuse split doesn't distinguish these sub-configurations as their own \
         shape, so no separate characteristic was invented for them.",
    ),
    (
        "Ordinary/realizational rule constraints (MaxApplicationCount/RequiredStemName/Blockable)",
        "a constraint-configuration variant of Affixation/RealizationalMorphology's own construct; \
         MaxApplicationCount/RequiredStemName/Blockable gate WHETHER an already-characterized rule \
         applies, they don't introduce a new FST-compilation shape of their own.",
    ),
    (
        "Tracing (TraceType)",
        "an engine debug/diagnostic feature (HC's trace output for developers), not a \
         grammar-compilation capability -- the typology research backing D1's table found no \
         capability basis for tracing as its own characteristic.",
    ),
];

/// Every `CharacteristicKind` the cross-check reasons over — literally `CharacteristicKind::ALL`,
/// not the narrower `Disposition::Proven` subset, which made the cross-check vacuous for most of
/// the ledger. Kept as a named function (rather than every caller reaching
/// for `CharacteristicKind::ALL` directly) so call sites read as making a deliberate scope choice,
/// matching this file's own established naming.
pub fn supported_kinds() -> Vec<CharacteristicKind> {
    CharacteristicKind::ALL.to_vec()
}

/// One `CharacteristicKind`'s cross-check outcome (deliverable 2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoverageStatus {
    /// At least one of `construct_ids_for`'s ids is in the caller's passing-covered set.
    Covered,
    /// `construct_ids_for` names at least one construct id, but none is in the caller's passing-covered set: supported without a covering, passing fixture.
    Uncovered,
    /// `construct_ids_for` returns an empty slice for this kind: no `constructs.txt` identifier corresponds to it, a gap in the mapping contract itself, distinct from `Uncovered`.
    Unmappable,
}

/// One row of the full report: a `CharacteristicKind`, its `Disposition` (kept explicit and
/// distinct from `status` so a reader — or a later staged flip — can tell `Proven`'s hard-error
/// rows apart from `ConfigPredicate`/`ConfirmOnly`'s "also needs a fixture, but not yet
/// admission-proven" rows without re-deriving anything), its mapped construct id(s) (possibly
/// empty), and the `CoverageStatus` that resolves to against the caller-supplied evidence set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoverageReportRow {
    pub kind: CharacteristicKind,
    pub disposition: Disposition,
    pub status: CoverageStatus,
    pub construct_ids: &'static [&'static str],
}

/// Deliverable 2, THE CROSS-CHECK: one `CoverageReportRow` per `supported_kinds` entry,
/// resolved against `passing_covered_constructs` — the `constructs.txt` identifiers exercised by
/// at least one word/parse whose engine output CURRENTLY MATCHES its fixture's declared ground
/// truth (see this module's own top-doc "What 'passing' means here").
///
/// A pure function deliberately kept free of any fixture-loading or engine-replay dependency, so
/// it stays cheaply unit-testable with hand-built sets.
pub fn supported_coverage_report(
    passing_covered_constructs: &HashSet<&str>,
) -> Vec<CoverageReportRow> {
    supported_kinds()
        .into_iter()
        .map(|kind| {
            let construct_ids = construct_ids_for(kind);
            let status = if construct_ids.is_empty() {
                CoverageStatus::Unmappable
            } else if construct_ids
                .iter()
                .any(|c| passing_covered_constructs.contains(c))
            {
                CoverageStatus::Covered
            } else {
                CoverageStatus::Uncovered
            };
            CoverageReportRow {
                kind,
                disposition: kind.default_disposition(),
                status,
                construct_ids,
            }
        })
        .collect()
}

/// Convenience projection of `supported_coverage_report`: every `CharacteristicKind` whose
/// status is NOT `CoverageStatus::Covered` (i.e. `Uncovered` or `Unmappable` — both are "not
/// demonstrably covered by the evidence its own disposition demands today", the task's "gaps").
/// `tests/conformance_coverage_gate.rs` asserts this is empty against the real conformance corpus
/// and prints the full report either way.
pub fn supported_uncovered(passing_covered_constructs: &HashSet<&str>) -> Vec<CharacteristicKind> {
    supported_coverage_report(passing_covered_constructs)
        .into_iter()
        .filter(|row| row.status != CoverageStatus::Covered)
        .map(|row| row.kind)
        .collect()
}

/// Every `constructs.txt` row id mapped by MORE THAN ONE `CharacteristicKind` — computed
/// directly from `construct_ids_for` over `CharacteristicKind::ALL`, never a hardcoded list.
/// See this module's own "structural-witness gate" top-doc section for why this matters and what
/// it is the mechanical half of. Deterministic order (`BTreeMap`) so callers/tests get stable
/// output regardless of `CharacteristicKind::ALL`'s own declaration order.
pub fn shared_construct_ids() -> Vec<(&'static str, Vec<CharacteristicKind>)> {
    let mut by_id: std::collections::BTreeMap<&'static str, Vec<CharacteristicKind>> =
        std::collections::BTreeMap::new();
    for &kind in CharacteristicKind::ALL {
        for &id in construct_ids_for(kind) {
            by_id.entry(id).or_default().push(kind);
        }
    }
    by_id
        .into_iter()
        .filter(|(_, kinds)| kinds.len() > 1)
        .collect()
}

/// One at-risk shared id's structural witness: a predicate over the LOADED grammar model that
/// decides whether a grammar structurally exhibits `finer_kind` — independent of any
/// `exercises:` tag. See `registered_structural_witnesses` for today's three, and each
/// predicate function's own doc for exactly where it reads its facts from.
pub struct StructuralWitness {
    pub construct_id: &'static str,
    /// The finer characteristic sharing `construct_id` that this predicate specifically pins
    /// structural evidence for. The coarser sibling needs no predicate of its own — an ordinary
    /// passing fixture already proves it, with no inheritance risk in that direction.
    pub finer_kind: CharacteristicKind,
    pub predicate: fn(&Grammar) -> bool,
}

impl std::fmt::Debug for StructuralWitness {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("StructuralWitness")
            .field("construct_id", &self.construct_id)
            .field("finer_kind", &self.finer_kind)
            .finish()
    }
}

/// `CharacteristicKind::UnorderedMorphRuleApplication`'s structural predicate: does any stratum
/// in the loaded `Grammar` declare `morphologicalRuleOrder="unordered"`
/// (`MorphRuleOrder::Unordered`, `pg_grammar::load`'s own parse of that attribute)? Reads the
/// LOADED model (`StratumDef::mrule_order`), never the raw XML — the same field
/// `tests/cover_unordered_morph_rules.rs` asserts against directly.
pub fn grammar_has_unordered_stratum(g: &Grammar) -> bool {
    g.strata
        .iter()
        .any(|s| s.mrule_order == MorphRuleOrder::Unordered)
}

/// `CharacteristicKind::Epenthesis`'s structural predicate: does any phonological rewrite rule
/// in the loaded `Grammar` have an EMPTY `PhoneticInput` — `pg_grammar::model::RewriteRuleDef`'s
/// own doc: "empty pattern if absent (epenthesis rules)"? Reads the LOADED model
/// (`RewriteRuleDef::lhs.nodes.is_empty()`), not a regex over `grammar.xml`'s `<PhoneticInput/>`
/// tag — deliberately: the DTD's insertion-only convention is that an ABSENT/empty
/// `<PhoneticInput>` element compiles to an empty `pg_grammar::model::Pattern` (zero
/// `pg_grammar::model::PatternNode`s), and reading the compiled model is the same fact
/// `tests/epenthesis_structural_route_containment.rs::fixture_has_epenthesis_and_composes_to_confirm_only`
/// already asserts on directly, rather than this gate re-deriving its own independent (and
/// possibly drifting) idea of what "empty" looks like in the source XML — e.g. a
/// self-closing `<PhoneticInput/>` vs. an empty `<PhoneticInput><PhoneticSequence/></PhoneticInput>`
/// are two different XML spellings of the identical loaded fact, and only the loaded model
/// treats them identically for free.
pub fn grammar_has_empty_lhs_rewrite_rule(g: &Grammar) -> bool {
    g.prules
        .iter()
        .any(|pr| matches!(pr, PhonRuleDef::Rewrite(r) if r.lhs.nodes.is_empty()))
}

/// `CharacteristicKind::CircumfixOutputAction`'s structural predicate: does ANY allomorph of ANY
/// morphological rule in the loaded `Grammar` classify as `Role::CircumfixPrefix` under
/// `crate::emit::classify_affix` — the COMPILER'S OWN classifier, called here directly rather
/// than re-implemented, so this gate and the compiler cannot drift apart. Deliberately scans
/// EVERY allomorph of every rule (`MorphRuleDef::affix_allomorphs`), not just allomorph 0 —
/// `crate::emit::rule_role` (the compiler's OWN candidate-selection path) classifies a rule by its
/// FIRST allomorph only, so a rule whose non-first allomorph is circumfix-shaped is a real,
/// order-of-declaration-dependent gap on the COMPILE side — this predicate must not repeat that
/// gap on the GATE side too, or a circumfix-shaped allomorph hiding behind a non-circumfix
/// allomorph 0 would make this witness silently fail to find a fixture that visibly has one.
pub fn grammar_has_circumfix_shaped_allomorph(g: &Grammar) -> bool {
    g.mrules.iter().any(|def| {
        def.affix_allomorphs().is_some_and(|allomorphs| {
            allomorphs
                .iter()
                .any(|a| crate::emit::classify_affix(&a.rhs) == crate::emit::Role::CircumfixPrefix)
        })
    })
}

pub fn grammar_has_overwrite_mpr_group(g: &Grammar) -> bool {
    g.mpr_groups
        .iter()
        .any(|group| group.output == MprGroupOutput::Overwrite)
}

/// The live `StructuralWitness`es — one per `shared_construct_ids` entry.
pub fn registered_structural_witnesses() -> Vec<StructuralWitness> {
    vec![
        StructuralWitness {
            construct_id: construct_ids_for(CharacteristicKind::UnorderedMorphRuleApplication)[0],
            finer_kind: CharacteristicKind::UnorderedMorphRuleApplication,
            predicate: grammar_has_unordered_stratum,
        },
        StructuralWitness {
            construct_id: construct_ids_for(CharacteristicKind::Epenthesis)[0],
            finer_kind: CharacteristicKind::Epenthesis,
            predicate: grammar_has_empty_lhs_rewrite_rule,
        },
        StructuralWitness {
            construct_id: construct_ids_for(CharacteristicKind::CircumfixOutputAction)[0],
            finer_kind: CharacteristicKind::CircumfixOutputAction,
            predicate: grammar_has_circumfix_shaped_allomorph,
        },
        StructuralWitness {
            construct_id: construct_ids_for(CharacteristicKind::MprGroupOverwrite)[0],
            finer_kind: CharacteristicKind::MprGroupOverwrite,
            predicate: grammar_has_overwrite_mpr_group,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every `CharacteristicKind` must be reachable from `construct_ids_for` without panicking end to end for the full `ALL` list.
    #[test]
    fn construct_ids_for_is_callable_for_every_kind() {
        for &kind in CharacteristicKind::ALL {
            let _ = construct_ids_for(kind);
        }
    }

    /// `supported_kinds` must be exactly `CharacteristicKind::ALL`; narrowing to the `Proven` subset would make the cross-check vacuous for most of the ledger.
    #[test]
    fn supported_kinds_is_exactly_characteristic_kind_all() {
        let supported = supported_kinds();
        assert_eq!(supported, CharacteristicKind::ALL.to_vec());
        // Sanity: strictly wider than the old Proven-only filter, guarding against silently narrowing this back down.
        let proven_only = CharacteristicKind::ALL
            .iter()
            .copied()
            .filter(|k| k.default_disposition() == Disposition::Proven)
            .count();
        assert!(supported.len() > proven_only);
    }

    /// With an empty evidence set, every kind must be `Uncovered` or `Unmappable`, never `Covered`.
    #[test]
    fn empty_evidence_sets_yield_no_covered_rows() {
        let covered: HashSet<&str> = HashSet::new();
        let report = supported_coverage_report(&covered);
        assert!(!report.is_empty());
        for row in &report {
            assert_ne!(row.status, CoverageStatus::Covered, "{:?}", row.kind);
        }
    }

    /// After G9, no `CharacteristicKind` is `Unmappable`; unlike `Covered`, this depends only on `construct_ids_for` being non-empty, not on caller-supplied evidence.
    #[test]
    fn zero_unmappable_after_g9() {
        let covered: HashSet<&str> = HashSet::new();
        let report = supported_coverage_report(&covered);
        let unmappable: Vec<CharacteristicKind> = report
            .iter()
            .filter(|r| r.status == CoverageStatus::Unmappable)
            .map(|r| r.kind)
            .collect();
        assert!(
            unmappable.is_empty(),
            "G9 must leave zero Unmappable kinds; found {unmappable:?}"
        );
        for &kind in CharacteristicKind::ALL {
            assert!(
                !construct_ids_for(kind).is_empty(),
                "{kind:?} still has no constructs.txt mapping after G9"
            );
        }
    }

    /// Feeding in every construct id `construct_ids_for` ever names must make every kind `Covered`.
    #[test]
    fn fully_evidenced_sets_cover_every_kind() {
        let mut covered: HashSet<&str> = HashSet::new();
        for &kind in CharacteristicKind::ALL {
            for &id in construct_ids_for(kind) {
                covered.insert(id);
            }
        }
        let report = supported_coverage_report(&covered);
        for row in &report {
            assert_eq!(
                row.status,
                CoverageStatus::Covered,
                "{:?} has mapped construct ids {:?} but was not Covered",
                row.kind,
                row.construct_ids
            );
        }
    }

    /// `MprGroupOverwrite` shares `"MPR features/groups"` with `MprGroupAppend`, the shared-id inheritance `registered_structural_witnesses` pins structurally rather than by disposition.
    #[test]
    fn overwrite_row_uses_passing_fixture_evidence() {
        let mut covered: HashSet<&str> = HashSet::new();
        for &id in construct_ids_for(CharacteristicKind::MprGroupAppend) {
            covered.insert(id);
        }
        let report = supported_coverage_report(&covered);
        let overwrite_row = report
            .iter()
            .find(|r| r.kind == CharacteristicKind::MprGroupOverwrite)
            .expect("MprGroupOverwrite must appear in the ledger-wide report");
        assert_eq!(overwrite_row.status, CoverageStatus::Covered);
    }

    /// `supported_uncovered` is exactly the non-`Covered` projection of the same report.
    #[test]
    fn supported_uncovered_matches_report_non_covered_rows() {
        let covered: HashSet<&str> = HashSet::new();
        let report = supported_coverage_report(&covered);
        let uncovered = supported_uncovered(&covered);
        let expected: Vec<CharacteristicKind> = report
            .iter()
            .filter(|r| r.status != CoverageStatus::Covered)
            .map(|r| r.kind)
            .collect();
        assert_eq!(uncovered, expected);
    }

    // Structural-witness gate, generic non-fixture half; the fixture-scanning half lives in tests/structural_witness_gate.rs.

    /// `shared_construct_ids` must find the known four shared ids today, pinning the exact shape so a silent change to `construct_ids_for` shows up here too.
    #[test]
    fn shared_construct_ids_finds_the_four_known_pairs() {
        let shared = shared_construct_ids();
        let pairs_containing = |a: CharacteristicKind, b: CharacteristicKind| {
            shared
                .iter()
                .any(|(_, kinds)| kinds.contains(&a) && kinds.contains(&b))
        };
        assert!(
            pairs_containing(
                CharacteristicKind::OrderedMorphRuleApplication,
                CharacteristicKind::UnorderedMorphRuleApplication
            ),
            "{shared:?}"
        );
        assert!(
            pairs_containing(
                CharacteristicKind::IterativeRewrite,
                CharacteristicKind::Epenthesis
            ),
            "{shared:?}"
        );
        assert!(
            pairs_containing(
                CharacteristicKind::Affixation,
                CharacteristicKind::CircumfixOutputAction
            ),
            "{shared:?}"
        );
        assert!(
            pairs_containing(
                CharacteristicKind::MprGroupAppend,
                CharacteristicKind::MprGroupOverwrite
            ),
            "{shared:?}"
        );
        assert_eq!(shared.len(), 4, "{shared:?}");
    }

    /// The generic drift guard: every shared id must have a registered `StructuralWitness`, computed with no hardcoded id list, so a new shared-id pair with no structural predicate fails loudly.
    #[test]
    fn every_shared_id_has_a_registered_structural_witness() {
        let at_risk = shared_construct_ids();
        assert!(
            !at_risk.is_empty(),
            "the at-risk-shared-id scan found nothing -- construct_ids_for's shape changed and \
             this check went vacuous, which is worse than a failure (see this module's own \
             top-doc on silent rot)"
        );

        let registered: HashSet<&str> = registered_structural_witnesses()
            .iter()
            .map(|w| w.construct_id)
            .collect();
        assert!(
            !registered.is_empty(),
            "no structural witnesses registered at all"
        );

        let missing: Vec<String> = at_risk
            .iter()
            .filter(|(id, _)| !registered.contains(id))
            .map(|(id, kinds)| {
                format!("{id:?} (shared by {kinds:?}) has no registered StructuralWitness")
            })
            .collect();
        assert!(
            missing.is_empty(),
            "new at-risk shared construct id(s) with no structural witness -- add one to \
             registered_structural_witnesses before trusting these ids' Covered status:\n  {}",
            missing.join("\n  ")
        );
    }

    /// Each witness's `construct_id` must be one of `construct_ids_for`'s ids for its own `finer_kind`, catching a witness pointing at the wrong kind's id.
    #[test]
    fn each_registered_witness_construct_id_matches_its_finer_kind() {
        for w in registered_structural_witnesses() {
            assert!(
                construct_ids_for(w.finer_kind).contains(&w.construct_id),
                "{w:?}: construct_id is not among construct_ids_for(finer_kind)"
            );
        }
    }
}
