//! Task 5.1 of `openspec/changes/add-capability-characteristics-check` (ADR 0001,
//! `docs/adr/0001-honest-capability-boundary.md`): the conformance-coverage cross-check, shipped
//! here as a **NON-BLOCKING, advisory preview** — the same non-blocking-first pattern
//! [`crate::capability`]'s own Step 1 (`characterize`, purely additive) → Step 2
//! (`compose_envelope`, CHECK-ONLY) → a later, deliberate compile-blocking step already used.
//!
//! ADR 0001, verbatim: *"'Supported' is mechanically gated on passing conformance coverage... CI
//! cross-checks the capability registry (the source-controlled, per-construct
//! supported/unsupported contract)... against conformance coverage (`constructs.txt` / per-word
//! `exercises:` / `rules.csv`), and marking anything supported without a covering, passing fixture
//! **breaks the build**."* This module supplies the mapping (deliverable 1) and the pure
//! cross-check function (deliverable 2) that claim answers; **nothing in this crate or its test
//! suite yet enforces `gaps.is_empty()`** — see "End state" below.
//!
//! # The two sides of the cross-check
//! - **The registry side**: [`crate::capability::CharacteristicKind`] + [`crate::capability::
//!   CharacteristicKind::default_disposition`] — [`Disposition::Proven`] is today's actual
//!   "supported (admission-proven)" set (design.md's table); `ConfirmOnly`/`ConfigPredicate`/
//!   `FailClosed` are compiled-or-relied-upon capabilities in their own right, just not
//!   admission-proven — see "G8: widening the cross-check ledger-wide" below for why this module
//!   now reasons about all four dispositions, not `Proven` alone.
//! - **The coverage side**: `machine/conformance/constructs.txt`'s flat checklist of construct
//!   identifiers, which every fixture's `words.yaml` `exercises:` entries (per-word AND per-parse,
//!   `pg_conformance_fixtures::{WordEntry, ParseEntry}`) are supposed to draw verbatim from
//!   (`constructs.txt`'s own header comment). `coverage.csv`/`rules.csv` are the C# oracle's own
//!   GENERATED cross-reference of the same data — this module does not read those two files
//!   directly (they are regenerated by `dotnet run ... --coverage-report`, a tool this Rust
//!   workspace does not invoke), it re-derives the same "which construct ids are exercised"
//!   question straight from `words.yaml`, which is the actual committed ground truth.
//!
//! # G8: widening the cross-check ledger-wide
//! Before this step, [`supported_kinds`] scoped itself to the 6 [`Disposition::Proven`] kinds
//! only — narrower than the ledger's 20 rows ([`crate::capability::CharacteristicKind::ALL`]).
//! That made the cross-check either **vacuous** (14 of 20 rows were never asked about at all) or
//! **misleading**: every row, `Proven` or not, was graded against the SAME "does a passing
//! analysis fixture exist" yardstick — which is simply the wrong question for a
//! [`Disposition::FailClosed`] construct (nothing compiles for it; there can never BE a passing
//! analysis fixture). Concretely, [`CharacteristicKind::MprGroupOverwrite`] (`FailClosed`) and
//! [`CharacteristicKind::MprGroupAppend`] (`ConfirmOnly`) both map to the same `constructs.txt`
//! id, `"MPR features/groups"` — so under the old uniform rule, an `MprGroupAppend` passing
//! fixture could make `MprGroupOverwrite` show falsely `Covered` too, despite `Overwrite` being
//! refused at compile time and never analyzed by anything.
//!
//! [`supported_kinds`] now returns every [`CharacteristicKind`] ([`crate::capability::
//! CharacteristicKind::ALL`]), and [`evidence_requirement_for`] encodes ADR 0001's honest
//! per-disposition rule as code: `Proven`/`ConfigPredicate`/`ConfirmOnly` all still need a
//! covering, PASSING analysis fixture ([`EvidenceRequirement::PassingFixture`] — the same
//! requirement, kept distinguishable from `Proven` via [`CoverageReportRow::disposition`] so a
//! later flip can stage `Proven` first); `FailClosed` needs a REFUSAL witness instead
//! ([`EvidenceRequirement::RefusalWitness`] — a fixture/test proving `compose_envelope` genuinely
//! refuses the construct, never a passing fixture). [`supported_coverage_report`] takes two
//! separate evidence sets (one per requirement) so the two can never cross-contaminate.
//! **Still advisory** — this widening does not flip anything to build-breaking; see "End state"
//! below.
//!
//! # What "passing" means here (a judgment call, flagged)
//! ADR 0001 says a construct needs "a covering, **passing** fixture" — not merely a fixture that
//! *mentions* the construct in an `exercises:` tag. This module itself takes no position on how
//! "passing" is established (it is a pure function over a caller-supplied
//! `passing_covered_constructs: &HashSet<&str>>`), so the actual engine-replay work stays a
//! dev-dependency-only concern: `tests/conformance_coverage_gate.rs` (this crate) builds that set
//! by replaying every discovered fixture (`pg_conformance_fixtures::discover`) against
//! `pg_parse::Morpher` — the SAME oracle `pg-parse`'s own `conformance_fixtures_gate.rs` already
//! runs the full suite against — and only credits a word's/parse's `exercises:` tags toward
//! coverage when that word's engine output actually matches the fixture's declared ground truth
//! signature. A currently-*failing* word's `exercises:` tags do not count. The analogous "refusal
//! witness" evidence ([`EvidenceRequirement::RefusalWitness`]) is NOT established by fixture
//! replay at all — today it lives in [`crate::coverage_ledger::containment_evidence_for`]'s
//! curated [`crate::coverage_ledger::ContainmentEvidenceKind::RefusalWitness`] citations (a
//! hand-reviewed table naming a specific Rust test, e.g. `tests/cover_mpr_groups.rs::
//! overwrite_group_composes_to_refuse`), which the caller is responsible for translating into a
//! `refusal_witnessed_kinds: &HashSet<CharacteristicKind>`.
//!
//! # The mapping (deliverable 1 — THE CONTRACT)
//! [`construct_ids_for`] is hand-authored and exhaustively matched (no catch-all arm — adding a
//! [`CharacteristicKind`] variant breaks this file's build, same discipline `characterize`/
//! `default_disposition` already hold themselves to). Before G9 (`machine` PR
//! sillsdev/machine#465), three kinds returned an **empty slice** —
//! [`CharacteristicKind::LeftToRightRewrite`], [`CharacteristicKind::RightToLeftRewrite`], and
//! [`CharacteristicKind::SubruleGating`] ([`CharacteristicKind::MultiTable`] was the fourth,
//! already documented separately below) — because `constructs.txt` had no row distinguishing
//! rewrite direction or subrule-level MPR/POS gating as its own tagged phenomenon. G9 added the
//! four missing rows upstream and this function now maps all four; see [`construct_ids_for`]'s own
//! per-arm doc for exactly which row each maps to and why the old mapping was genuinely absent
//! rather than mismapped. [`ORPHAN_CONSTRUCT_ROWS`] is the mirror-image list this same audit
//! surfaced — 12 `constructs.txt` rows with NO corresponding `CharacteristicKind`, deliberately
//! left unmapped (not invented) with a documented reason each.
//! [`CoverageStatus::Unmappable`] surfaces a construct-id-less kind separately from
//! [`CoverageStatus::Uncovered`] (a real construct id exists, but the required evidence is
//! missing) so a reader never conflates "nobody has produced the evidence yet" with "there is
//! nothing to produce evidence FOR." After G9, zero kinds are `Unmappable` (see
//! `zero_unmappable_after_g9`).
//!
//! # Investigation finding: does `words.yaml` cleanly support "construct X is exercised by a
//! passing fixture"?
//! **Yes, with one caveat.** `exercises:` is a first-class, already-populated field on both
//! `WordEntry` and `ParseEntry` (`pg_conformance_fixtures::{WordEntry, ParseEntry}`), populated
//! from `constructs.txt`'s verbatim identifiers today (`coverage.csv` proves this: every
//! `construct` column value there is a literal `constructs.txt` line). So the coverage metadata
//! does NOT need new fixture tagging to answer "is construct X exercised anywhere" — that much is
//! already clean. The caveat is "passing": `exercises:` tags a word/parse with a construct
//! regardless of whether any given ENGINE currently gets that word right — the tag is
//! ground-truth metadata about the FIXTURE, not a per-engine pass/fail record. Answering "passing"
//! therefore requires actually replaying the fixture (this crate's test does exactly that against
//! `pg_parse::Morpher`), rather than reading a static column — a real, if modest, gap between what
//! `words.yaml` states and what this cross-check needs, closed here by re-deriving pass/fail via
//! replay rather than by asking for new fixture tagging.
//!
//! # End state (deferred, NOT this step)
//! Task 5.1 proper turns this into a hard CI gate — mechanically, replacing this module's non-
//! assertion with `assert!(supported_uncovered(&covered, &witnessed).is_empty(), "...")` in
//! `tests/conformance_coverage_gate.rs`. Deferred here deliberately: gaps exist today (see that
//! test's own report), and ADR 0001's own non-blocking-first precedent (`compose_envelope`/
//! `CompileDecision` were CHECK-ONLY for a full step before any compile path consulted them) is
//! the model this task explicitly asks to repeat. G8 makes the widened report accurate and
//! flip-ready but deliberately does NOT flip it — a real flip should stage `Proven` rows (a hard
//! error) ahead of `ConfigPredicate`/`ConfirmOnly` rows (also required, but distinguishable via
//! `disposition` so they can gate on a later date), per the task's own framing.

use std::collections::HashSet;

use crate::capability::{CharacteristicKind, Disposition};

/// Deliverable 1, THE CONTRACT: `kind`'s corresponding `machine/conformance/constructs.txt`
/// identifier(s), verbatim (byte-for-byte matching what a `words.yaml` `exercises:` entry would
/// carry — see `constructs.txt`'s own header: "A line's text (verbatim, including punctuation) is
/// the key"). Exhaustively matched (no catch-all): adding a [`CharacteristicKind`] variant without
/// adding an arm here breaks this crate's build, same discipline
/// [`CharacteristicKind::default_disposition`] already holds itself to.
///
/// An empty slice is a deliberate, documented "no corresponding coverage identifier exists" —
/// [`CoverageStatus::Unmappable`]'s trigger, not an oversight:
/// - [`CharacteristicKind::MultiTable`]: `constructs.txt` has no row tagging "more than one
///   `CharacterDefinitionTable`, each stratum's own" as its own phenomenon — see this function's
///   own match arm for the two near-miss rows considered and rejected.
/// - [`CharacteristicKind::LeftToRightRewrite`] / [`CharacteristicKind::RightToLeftRewrite`]:
///   `constructs.txt`'s `RewriteRule Iterative (...)`/`RewriteRule Simultaneous` rows tag
///   *multiple-application order*, not *directionality* — no row anywhere names "left-to-right" or
///   "right-to-left" as its own tagged phenomenon, so no fixture author has anything to write in
///   an `exercises:` list for direction specifically, however many `Dir::RightToLeft` rules a
///   grammar has.
/// - [`CharacteristicKind::SubruleGating`]: this characteristic is triggered by a
///   `RewriteSubruleDef` declaring `required_pos`/`required_mpr`/`excluded_mpr` — a *phonological*
///   subrule's own MPR/POS gate. `constructs.txt`'s `MPR features/groups` row is the closest
///   textual match, but every `coverage.csv` row actually tagged with it exercises a
///   *morphological* `MprGroup` (`MprGroupAppend`/`MprGroupOverwrite`'s own territory — e.g.
///   Velamba's `mrExtX`/`mrEndW`), never a gated phonological subrule; mapping `SubruleGating` onto
///   that row would overclaim coverage that was never actually exercised for THIS characteristic.
///   No row distinctly tags phonological-subrule-level gating today.
///
/// One further judgment call, NOT an empty mapping: `constructs.txt`'s `"AffixProcessRule:
/// subtraction/truncation"` row is folded into [`CharacteristicKind::Affixation`]'s mapping rather
/// than given its own `CharacteristicKind`. D1's characterizer (`capability.rs`) has no distinct
/// characteristic for plain (single-part-LHS) truncation — [`CharacteristicKind::
/// CircumfixOutputAction`]'s own trigger (`allomorph_drops_lhs_material`) explicitly early-returns
/// `false` for `lhs.len() <= 1`, so an ordinary subtractive/truncating affix characterizes as
/// plain `Affixation` (Proven), same as any other `AffixProcessRule`. This is not this module
/// inventing a characteristic — it is documenting where `capability.rs`'s own granularity already
/// lands truncation, so the mapping is honest about what `Affixation`'s `Proven` disposition is
/// actually claiming to cover.
///
/// # G9 update (`machine` PR sillsdev/machine#465, branch `g9-add-missing-construct-rows`)
/// The four characteristics that used to return an empty slice here — [`CharacteristicKind::
/// LeftToRightRewrite`], [`CharacteristicKind::RightToLeftRewrite`], [`CharacteristicKind::
/// SubruleGating`], [`CharacteristicKind::MultiTable`] — now map to four NEW `constructs.txt`
/// rows added upstream specifically to close this gap (this function's own previous doc explained
/// exactly why each was a genuine, deliberate non-mapping; that reasoning is preserved below per
/// arm, now paired with the row that was added to resolve it). No other characteristic's mapping
/// changed. [`CharacteristicKind::MultiTable`] is exhaustively re-verified as the true empty-
/// mapping was NOT a permanent property — see [`ledger_wide_uncovered_today`] below for which rows
/// (mapped or not) still lack a *passing/refusal-witnessed* fixture even after this mapping fix.
pub fn construct_ids_for(kind: CharacteristicKind) -> &'static [&'static str] {
    use CharacteristicKind::*;
    match kind {
        Affixation => &[
            "AffixProcessRule: prefix/suffix/circumfix/infix",
            "AffixProcessRule: subtraction/truncation",
        ],
        RealizationalMorphology => &["RealizationalAffixProcessRule"],
        Compounding => &["CompoundingRule"],
        OrderedMorphRuleApplication => &["Stratum (Linear/Unordered rule order)"],
        UnorderedMorphRuleApplication => &["Stratum (Linear/Unordered rule order)"],
        MprGroupAppend => &["MPR features/groups"],
        MprGroupOverwrite => &["MPR features/groups"],
        IterativeRewrite => &["RewriteRule Iterative (epenthesis/deletion/feature/expansion/merge)"],
        SimultaneousRewrite => &["RewriteRule Simultaneous"],
        // `compile-right-to-left-rewrites`/G9: `constructs.txt`'s `RewriteRule Iterative(...)`/
        // `RewriteRule Simultaneous` rows tag *multiple-application order*, not *directionality* --
        // no row named direction as its own phenomenon existed before G9. Added upstream as
        // `"RewriteRule direction (Dir): left-to-right"` / `"...right-to-left"`.
        LeftToRightRewrite => &["RewriteRule direction (Dir): left-to-right"],
        RightToLeftRewrite => &["RewriteRule direction (Dir): right-to-left"],
        Metathesis => &["MetathesisRule"],
        Epenthesis => &["RewriteRule Iterative (epenthesis/deletion/feature/expansion/merge)"],
        // G9: this characteristic is triggered by a `RewriteSubruleDef` declaring
        // `required_pos`/`required_mpr`/`excluded_mpr` -- a *phonological* subrule's own MPR/POS
        // gate, distinct from `MprGroupAppend`/`MprGroupOverwrite`'s *morphological* `MprGroup`
        // territory (every `coverage.csv` row tagged with the pre-G9 closest-match `"MPR
        // features/groups"` row actually exercised a `MprGroup`, never a gated phonological
        // subrule -- mapping onto that row would have overclaimed coverage never actually
        // exercised for THIS characteristic, so no mapping existed before G9). Added upstream as
        // `"RewriteSubruleDef gating: required/excluded POS or MPR at the subrule level"`.
        SubruleGating => &["RewriteSubruleDef gating: required/excluded POS or MPR at the subrule level"],
        CircumfixOutputAction => &["AffixProcessRule: prefix/suffix/circumfix/infix"],
        Reduplication => &["AffixProcessRule: reduplication (ReduplicationHint)"],
        CoOccurrenceConstraint => &["MorphemeCoOccurrenceRule/AllomorphCoOccurrenceRule"],
        NaturalClassDefinition => &[
            "NaturalClass: Segments vs FeatureNaturalClass/SegmentNaturalClass precision",
        ],
        // `fix-multitable-fst-compilation`/G9: the two PRE-EXISTING rows that mention
        // `CharacterDefinitionTable` at all -- "Boundary markers" and "pattern shapes: optional
        // group / Kleene star" -- are about segmentation/pattern constructs WITHIN one table, not
        // about multiple tables disagreeing across strata, so neither was a valid mapping target;
        // no row distinctly tagged multi-table stratification before G9. Added upstream as
        // `"CharacterDefinitionTable: more than one table, one per stratum"`.
        MultiTable => &["CharacterDefinitionTable: more than one table, one per stratum"],
        // `compile-bounded-fst-quantifiers`: `constructs.txt`'s own "optional group / Kleene star"
        // row is exactly `PatternNode::Quantifier` (`<OptionalSegmentSequence min max>`) -- unlike
        // `MultiTable`/`LeftToRightRewrite`/etc above, this construct already had a distinctly-
        // tagged coverage identifier before G9.
        QuantifierPattern => &["CharacterDefinitionTable pattern shapes: optional group / Kleene star"],
    }
}

/// The 12 `constructs.txt` rows that name a genuine construct with NO corresponding
/// [`CharacteristicKind`] at all (the mirror image of the empty-slice arms [`construct_ids_for`]
/// used to have before G9 — there, a characteristic existed with no row; here, a row exists with
/// no characteristic). Per the G9 task's own instruction: **do not invent characteristics for
/// these** — some are genuinely not compiler/FST-capability concerns at all. This function exists
/// purely as living documentation (nothing calls it at runtime; no test asserts these ARE the only
/// 12 — that would require parsing `constructs.txt` at build time, which this crate deliberately
/// does not do, per [`construct_ids_for`]'s own "hand-authored, verbatim" contract) — see each
/// tuple's second field for why no `CharacteristicKind` was added for it.
pub const ORPHAN_CONSTRUCT_ROWS: &[(&str, &str)] = &[
    (
        "MorphologicalOutputAction: CopyFromInput/InsertSegments",
        "an ordinary output-action primitive already exercised as part of Affixation/\
         CircumfixOutputAction coverage; D1's table has no distinct admission-gated characteristic \
         for individual OutputAction variants (they collapse into whichever MorphRuleDef/\
         AffixAllomorphDef characteristic uses them).",
    ),
    (
        "MorphologicalOutputAction: ModifyFromInput/InsertSimpleContext",
        "same reasoning as \"CopyFromInput/InsertSegments\" above -- an ordinary output-action \
         primitive, not its own gated phenomenon.",
    ),
    (
        "Affix template slots (obligatory/disjunctive/ordering)",
        "a morphotactic templating detail already covered generically by Affixation/\
         OrderedMorphRuleApplication proposing; no distinct CharacteristicKind carves out \
         slot-level obligatoriness/ordering as its own admission-filtered phenomenon.",
    ),
    (
        "Boundary markers (CharacterDefinitionTable)",
        "segmentation/tokenization detail within one CharacterDefinitionTable -- purely \
         representational (how raw input is chunked into segments), not itself a proposer/confirm \
         capability axis D1's table gates on (same standing as NaturalClassDefinition's own \
         \"representational only, no capability implication either way\" framing, just not given \
         its own variant).",
    ),
    (
        "Guesser/LexicalGuess",
        "a runtime unknown-word heuristic (HC's guesser subsystem), not a compiled-FST capability; \
         no model.rs construct this crate's characterize() walks corresponds to it at all -- \
         outside this crate's characterization scope entirely.",
    ),
    (
        "Disjunctive allomorphs / free-fluctuation",
        "free variation among multiple allomorphs of one lexical entry is ordinary lexicon \
         branching, already exercised pervasively as part of Affixation coverage; not a \
         separately gated characteristic.",
    ),
    (
        "Stem names",
        "stem-name identity/assignment on a lexical entry is representational bookkeeping (a \
         label), not itself an admission-relevant characteristic; its only capability-relevant use \
         (constraining rule application via RequiredStemName) is \"Ordinary/realizational rule \
         constraints\"'s own territory below, not carved into its own CharacteristicKind.",
    ),
    (
        "Syntactic feature agreement (RequiredHeadFeatures/OutputHeadFeatures/RequiredFootFeatures/\
         OutputFootFeatures)",
        "ordinary confirm-time feature-unification, already assumed faithful per \
         IMPLEMENTATION-READINESS.md R1 (\"HermitCrab and the Rust model are assumed complete \
         apart from bug fixes\"); not a distinct FST-compilation capability axis this crate \
         characterizes.",
    ),
    (
        "Alpha-variable phonological environments (VariableFeature/AlphaVariables)",
        "alpha-variable (feature-agreement) environment matching is a rewrite-rule environment \
         detail, already covered generically by IterativeRewrite/SimultaneousRewrite fixtures; no \
         distinct CharacteristicKind carves out alpha-variable binding as its own admission-gated \
         phenomenon.",
    ),
    (
        "CompoundingRule constraints (MaxApplicationCount/Blockable/head-nonhead syntactic \
         features)",
        "a more granular constraint-configuration variant of CharacteristicKind::Compounding's own \
         construct (the plain \"CompoundingRule\" row); CompoundingRecursionSafePredicate's \
         admit/confirm/refuse split doesn't distinguish these sub-configurations as their own \
         shape, so no separate characteristic was invented for them.",
    ),
    (
        "Ordinary/realizational rule constraints (MaxApplicationCount/RequiredStemName/Blockable)",
        "a constraint-configuration variant of Affixation/RealizationalMorphology's own construct; \
         MaxApplicationCount/RequiredStemName/Blockable gate WHETHER an already-characterized rule \
         applies, they don't introduce a new FST-compilation shape of their own.",
    ),
    (
        "Tracing (TraceType)",
        "an engine debug/diagnostic feature (HC's trace output for developers), not a \
         grammar-compilation capability -- the typology research backing D1's table found no \
         capability basis for tracing as its own characteristic.",
    ),
];

/// **G8 ("widen the cross-check ledger-wide"):** every [`CharacteristicKind`] the cross-check
/// reasons over — literally `CharacteristicKind::ALL` (20 kinds), not the narrower
/// `Disposition::Proven`-only 6 this function returned before G8. Narrowing to `Proven` made the
/// cross-check either vacuous (14 of the ledger's 20 rows were never asked about at all) or
/// misleading (a `FailClosed` row like [`CharacteristicKind::MprGroupOverwrite`], had it been
/// asked, would have been graded by the SAME "passing analysis fixture" yardstick as `Proven` rows
/// — nothing compiles for a refused construct, so that yardstick can never honestly apply to it;
/// see [`evidence_requirement_for`]). Kept as a named function (rather than every caller reaching
/// for `CharacteristicKind::ALL` directly) so call sites read as making a deliberate scope choice,
/// matching this file's own established naming.
pub fn supported_kinds() -> Vec<CharacteristicKind> {
    CharacteristicKind::ALL.to_vec()
}

/// Which evidence shape a disposition's ADR 0001 honest, per-disposition rule (task G8) demands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EvidenceRequirement {
    /// [`Disposition::Proven`], [`Disposition::ConfigPredicate`], [`Disposition::ConfirmOnly`]:
    /// each is a compiled/relied-upon capability (a grammar CAN actually compile through it
    /// today), so each needs a covering, PASSING analysis fixture — the same requirement, even
    /// though only `Proven` is admission-proven. A build-breaking flip can and should stage these
    /// three differently (gate on `Proven` first); this module reports `disposition` on every row
    /// precisely so that staging is possible without re-deriving the report.
    PassingFixture,
    /// [`Disposition::FailClosed`]: nothing compiles for this construct by design (ADR 0005's
    /// indelible override is the only escape hatch), so a passing ANALYSIS fixture is not even the
    /// right kind of evidence to demand. Needs a REFUSAL witness instead — a fixture/test proving
    /// `compose_envelope` genuinely refuses whenever this construct is observed (e.g. `tests/
    /// cover_mpr_groups.rs::overwrite_group_composes_to_refuse`, the curated citation for
    /// [`CharacteristicKind::MprGroupOverwrite`] in [`crate::coverage_ledger::
    /// containment_evidence_for`]) — never a passing fixture, which cannot exist for a refused
    /// construct.
    RefusalWitness,
}

/// `disposition`'s [`EvidenceRequirement`] — the G8 honest per-disposition rule, as code.
/// Exhaustively matched (no catch-all): adding a [`Disposition`] variant breaks this build too.
pub fn evidence_requirement_for(disposition: Disposition) -> EvidenceRequirement {
    match disposition {
        Disposition::Proven | Disposition::ConfigPredicate | Disposition::ConfirmOnly => {
            EvidenceRequirement::PassingFixture
        }
        Disposition::FailClosed => EvidenceRequirement::RefusalWitness,
    }
}

/// One [`CharacteristicKind`]'s cross-check outcome (deliverable 2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoverageStatus {
    /// The evidence [`EvidenceRequirement`] demands was found: for [`EvidenceRequirement::
    /// PassingFixture`], at least one of [`construct_ids_for`]'s ids is in the caller's
    /// passing-covered set; for [`EvidenceRequirement::RefusalWitness`], the kind is in the
    /// caller's refusal-witnessed set.
    Covered,
    /// [`construct_ids_for`] names at least one construct id, but the evidence
    /// [`EvidenceRequirement`] demands was NOT found — a gap (ADR 0001's "marking anything
    /// supported without a covering, passing fixture" case, generalized to `FailClosed`'s own
    /// refusal-witness requirement).
    Uncovered,
    /// [`construct_ids_for`] returns an empty slice for this kind: no `constructs.txt` identifier
    /// corresponds to it at all, so no fixture -- however written -- could satisfy this cross-check
    /// for it today. A gap in the mapping contract itself, distinct from `Uncovered`. G9 closed
    /// this for the 4 kinds that used to be `Unmappable` for this reason; zero kinds are
    /// `Unmappable` for THIS reason after G9 (see `coverage_ledger`'s
    /// `zero_unmappable_rows_after_g9` test) — a kind can still show `Unmappable` if a future
    /// change reopens this gap, per this type's own no-catch-all mapping discipline.
    Unmappable,
}

/// One row of the full advisory report: a [`CharacteristicKind`], its [`Disposition`] and
/// resulting [`EvidenceRequirement`] (kept explicit and distinct from `status` so a reader — or a
/// later staged flip — can tell `Proven`'s hard-error rows apart from `ConfigPredicate`/
/// `ConfirmOnly`'s "also needs a fixture, but not yet admission-proven" rows and `FailClosed`'s
/// "needs a refusal witness, never a passing fixture" rows without re-deriving anything), its
/// mapped construct id(s) (possibly empty), and the [`CoverageStatus`] that resolves to against
/// the caller-supplied evidence sets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoverageReportRow {
    pub kind: CharacteristicKind,
    pub disposition: Disposition,
    pub evidence_requirement: EvidenceRequirement,
    pub status: CoverageStatus,
    pub construct_ids: &'static [&'static str],
}

/// Deliverable 2, THE CROSS-CHECK, **widened ledger-wide (G8)**: one [`CoverageReportRow`] per
/// [`supported_kinds`] entry (now literally every [`CharacteristicKind`]), resolved against TWO
/// caller-supplied evidence sets, selected per row by [`evidence_requirement_for`]:
/// - `passing_covered_constructs`: `constructs.txt` identifiers exercised by at least one
///   word/parse whose engine output CURRENTLY MATCHES its fixture's declared ground truth (see
///   this module's own top-doc "What 'passing' means here") — the evidence
///   [`EvidenceRequirement::PassingFixture`] rows (`Proven`/`ConfigPredicate`/`ConfirmOnly`) need.
/// - `refusal_witnessed_kinds`: [`CharacteristicKind`]s for which the caller has independently
///   established a genuine refusal witness exists (in practice, built from [`crate::
///   coverage_ledger::containment_evidence_for`]'s [`crate::coverage_ledger::
///   ContainmentEvidenceKind::RefusalWitness`] citations) — the evidence
///   [`EvidenceRequirement::RefusalWitness`] rows (`FailClosed`) need instead. Deliberately NOT
///   consulted for `PassingFixture` rows and vice versa: before this fix, every row (including
///   `FailClosed` ones) was graded uniformly against `passing_covered_constructs` alone, so a
///   `FailClosed` construct sharing a `constructs.txt` id with a `ConfirmOnly`/`Proven` sibling
///   (e.g. [`CharacteristicKind::MprGroupAppend`] and [`CharacteristicKind::MprGroupOverwrite`]
///   both map to `"MPR features/groups"`) could show `Covered` purely because the SIBLING's
///   passing fixture happened to tag the same shared id — a real, silent cross-contamination this
///   split makes structurally impossible.
///
/// A pure function deliberately kept free of any fixture-loading or engine-replay dependency, so
/// it stays cheaply unit-testable with hand-built sets.
pub fn supported_coverage_report(
    passing_covered_constructs: &HashSet<&str>,
    refusal_witnessed_kinds: &HashSet<CharacteristicKind>,
) -> Vec<CoverageReportRow> {
    supported_kinds()
        .into_iter()
        .map(|kind| {
            let disposition = kind.default_disposition();
            let evidence_requirement = evidence_requirement_for(disposition);
            let construct_ids = construct_ids_for(kind);
            let status = if construct_ids.is_empty() {
                CoverageStatus::Unmappable
            } else {
                let is_evidenced = match evidence_requirement {
                    EvidenceRequirement::PassingFixture => construct_ids
                        .iter()
                        .any(|c| passing_covered_constructs.contains(c)),
                    EvidenceRequirement::RefusalWitness => {
                        refusal_witnessed_kinds.contains(&kind)
                    }
                };
                if is_evidenced {
                    CoverageStatus::Covered
                } else {
                    CoverageStatus::Uncovered
                }
            };
            CoverageReportRow {
                kind,
                disposition,
                evidence_requirement,
                status,
                construct_ids,
            }
        })
        .collect()
}

/// Convenience projection of [`supported_coverage_report`]: every [`CharacteristicKind`] whose
/// status is NOT [`CoverageStatus::Covered`] (i.e. `Uncovered` or `Unmappable` — both are "not
/// demonstrably covered by the evidence its own disposition demands today", the task's "gaps").
/// **NON-BLOCKING**: callers must NOT assert this is empty yet — see this module's own top-doc
/// "End state". This is the "which rows would fail a flip today" list (task G8's own final
/// deliverable) — see `tests/conformance_coverage_gate.rs`'s own printed report for the concrete,
/// currently-computed list against the real conformance corpus.
pub fn supported_uncovered(
    passing_covered_constructs: &HashSet<&str>,
    refusal_witnessed_kinds: &HashSet<CharacteristicKind>,
) -> Vec<CharacteristicKind> {
    supported_coverage_report(passing_covered_constructs, refusal_witnessed_kinds)
        .into_iter()
        .filter(|row| row.status != CoverageStatus::Covered)
        .map(|row| row.kind)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every [`CharacteristicKind`] must be reachable from [`construct_ids_for`] without panicking
    /// (the exhaustive-match discipline is enforced by the compiler already; this test just proves
    /// the function is callable end to end for the full `ALL` list, matching the same
    /// belt-and-suspenders style `capability.rs`'s own `all_kinds_have_a_default_disposition` test
    /// uses for `default_disposition`).
    #[test]
    fn construct_ids_for_is_callable_for_every_kind() {
        for &kind in CharacteristicKind::ALL {
            let _ = construct_ids_for(kind);
        }
    }

    /// G8: [`supported_kinds`] must be EXACTLY `CharacteristicKind::ALL`, not the old
    /// `Proven`-only 6 — the whole point of "widen the cross-check ledger-wide".
    #[test]
    fn supported_kinds_is_exactly_characteristic_kind_all() {
        let supported = supported_kinds();
        assert_eq!(supported, CharacteristicKind::ALL.to_vec());
        // Sanity: this is a strictly wider set than the old Proven-only filter (guards against a
        // future edit silently narrowing this back down).
        let proven_only = CharacteristicKind::ALL
            .iter()
            .copied()
            .filter(|k| k.default_disposition() == Disposition::Proven)
            .count();
        assert!(supported.len() > proven_only);
    }

    /// [`evidence_requirement_for`] is exhaustive and matches the ADR 0001 rule literally:
    /// `FailClosed` needs a `RefusalWitness`, everything else needs a `PassingFixture`.
    #[test]
    fn evidence_requirement_matches_disposition_exactly() {
        for &kind in CharacteristicKind::ALL {
            let disposition = kind.default_disposition();
            let requirement = evidence_requirement_for(disposition);
            if disposition == Disposition::FailClosed {
                assert_eq!(requirement, EvidenceRequirement::RefusalWitness, "{kind:?}");
            } else {
                assert_eq!(requirement, EvidenceRequirement::PassingFixture, "{kind:?}");
            }
        }
    }

    /// With both evidence sets empty, every kind must be `Uncovered` (has mapped construct ids) or
    /// `Unmappable` (has none) — never `Covered`. Zero `Unmappable` rows remain after G9 (every
    /// kind now maps to a real `constructs.txt` row) — see `zero_unmappable_after_g9` below.
    #[test]
    fn empty_evidence_sets_yield_no_covered_rows() {
        let covered: HashSet<&str> = HashSet::new();
        let witnessed: HashSet<CharacteristicKind> = HashSet::new();
        let report = supported_coverage_report(&covered, &witnessed);
        assert!(!report.is_empty());
        for row in &report {
            assert_ne!(row.status, CoverageStatus::Covered, "{:?}", row.kind);
        }
    }

    /// G9: after adding the 4 missing `constructs.txt` rows and mapping them, NO
    /// [`CharacteristicKind`] is `Unmappable` any more — every one of the 20 rows now has a real
    /// `constructs.txt` identifier. This is a hard, unconditional assertion (unlike `Covered`,
    /// which depends on caller-supplied evidence sets): `Unmappable` depends only on
    /// [`construct_ids_for`] being non-empty.
    #[test]
    fn zero_unmappable_after_g9() {
        let covered: HashSet<&str> = HashSet::new();
        let witnessed: HashSet<CharacteristicKind> = HashSet::new();
        let report = supported_coverage_report(&covered, &witnessed);
        let unmappable: Vec<CharacteristicKind> = report
            .iter()
            .filter(|r| r.status == CoverageStatus::Unmappable)
            .map(|r| r.kind)
            .collect();
        assert!(
            unmappable.is_empty(),
            "G9 must leave zero Unmappable kinds; found {unmappable:?}"
        );
        for &kind in CharacteristicKind::ALL {
            assert!(
                !construct_ids_for(kind).is_empty(),
                "{kind:?} still has no constructs.txt mapping after G9"
            );
        }
    }

    /// Feeding in every construct id [`construct_ids_for`] ever names, PLUS every `FailClosed`
    /// kind as refusal-witnessed, must make every kind `Covered` (all 20 are mappable after G9).
    #[test]
    fn fully_evidenced_sets_cover_every_kind() {
        let mut covered: HashSet<&str> = HashSet::new();
        let mut witnessed: HashSet<CharacteristicKind> = HashSet::new();
        for &kind in CharacteristicKind::ALL {
            for &id in construct_ids_for(kind) {
                covered.insert(id);
            }
            if kind.default_disposition() == Disposition::FailClosed {
                witnessed.insert(kind);
            }
        }
        let report = supported_coverage_report(&covered, &witnessed);
        for row in &report {
            assert_eq!(
                row.status,
                CoverageStatus::Covered,
                "{:?} (requirement {:?}) has mapped construct ids {:?} but was not Covered",
                row.kind,
                row.evidence_requirement,
                row.construct_ids
            );
        }
    }

    /// The core G8 honesty guarantee: a `FailClosed` kind's status must depend ONLY on the
    /// refusal-witnessed set, never on `passing_covered_constructs` — even when a SIBLING kind
    /// (sharing the same `constructs.txt` id) is fully covered by a passing fixture. Regression
    /// test for the exact cross-contamination this split closes: before this fix,
    /// `MprGroupOverwrite` (`FailClosed`) could show `Covered` purely because `MprGroupAppend`
    /// (`ConfirmOnly`) shares its `"MPR features/groups"` construct id and had a passing fixture.
    #[test]
    fn fail_closed_row_never_covered_by_a_siblings_passing_fixture() {
        let mut covered: HashSet<&str> = HashSet::new();
        for &id in construct_ids_for(CharacteristicKind::MprGroupAppend) {
            covered.insert(id);
        }
        let witnessed: HashSet<CharacteristicKind> = HashSet::new(); // no refusal witness supplied
        let report = supported_coverage_report(&covered, &witnessed);
        let overwrite_row = report
            .iter()
            .find(|r| r.kind == CharacteristicKind::MprGroupOverwrite)
            .expect("MprGroupOverwrite must appear in the ledger-wide report");
        assert_eq!(
            overwrite_row.status,
            CoverageStatus::Uncovered,
            "MprGroupOverwrite must NOT be Covered by MprGroupAppend's passing fixture alone"
        );

        // Conversely, supplying ONLY the refusal witness (no passing fixture at all) is
        // sufficient -- proving the two evidence sets are properly decoupled in both directions.
        let empty_covered: HashSet<&str> = HashSet::new();
        let mut only_witnessed: HashSet<CharacteristicKind> = HashSet::new();
        only_witnessed.insert(CharacteristicKind::MprGroupOverwrite);
        let report2 = supported_coverage_report(&empty_covered, &only_witnessed);
        let overwrite_row2 = report2
            .iter()
            .find(|r| r.kind == CharacteristicKind::MprGroupOverwrite)
            .unwrap();
        assert_eq!(overwrite_row2.status, CoverageStatus::Covered);
    }

    /// [`supported_uncovered`] is exactly the non-`Covered` projection of the same report.
    #[test]
    fn supported_uncovered_matches_report_non_covered_rows() {
        let covered: HashSet<&str> = HashSet::new();
        let witnessed: HashSet<CharacteristicKind> = HashSet::new();
        let report = supported_coverage_report(&covered, &witnessed);
        let uncovered = supported_uncovered(&covered, &witnessed);
        let expected: Vec<CharacteristicKind> = report
            .iter()
            .filter(|r| r.status != CoverageStatus::Covered)
            .map(|r| r.kind)
            .collect();
        assert_eq!(uncovered, expected);
    }
}
