//! The emitter (plan `docs/fst-plan/foma-fst-plan.md` D3, P1 stage 1): `Grammar -> lexc source`.
//!
//! ## Structure: a faithful mirror of `hc-hybrid/src/trie.rs`'s morphotactics
//! This emitter reproduces the SAME morphotactic language `hc-hybrid`'s trie encodes (upward
//! deviations only — see "deliberate supersets" below), expressed as lexc continuation classes:
//!
//! - **Bare-root paths** (`trie.rs` `run()` "Bare-root paths"): every root allomorph directly
//!   accepting. Deviation (upward): trie gates bare roots on `bare_root_surfaces` non-empty
//!   (the obligatory-inflection check, which needs a live `Morpher`); this emitter admits every
//!   root bare — a superset; the verify pass (P2) prunes.
//! - **Template-less derivation section** (`trie.rs:1035-1063`): prefix derivation layer →
//!   every root → optional single compound root → suffix derivation layer → accept. Only built
//!   when the grammar has standalone derivation rules or compounding rules, like trie.
//! - **Per-template slot chains** (`trie.rs::classify_template`/`append_slots`,
//!   `trie.rs:871-959`): each template's slots are classified prefix/suffix by `slot_op`, the
//!   prefix list REVERSED to surface order, and each slot appears EXACTLY ONCE in its chain
//!   (optional slots add an epsilon skip) — this is what bounds zero-surface slot allomorphs to
//!   at most one tag per slot (the depth-N "bag" design this replaced admitted them at every
//!   level and overgenerated by six orders of magnitude on real Sena words — 2.5M candidates for
//!   `mbali` vs the engine's 8).
//! - **Derivation layers** (`trie.rs::build_derivation_layer`, `trie.rs:796-836`): the
//!   standalone (stratum-attached, non-template) affix rules, in a bounded chain of optional
//!   levels. Depth = the NUMBER OF RULES routed to that side (min 2) — deeper than trie's
//!   `deriv_depth = 2` (an upward deviation, found by the recall gate: Sena's corpus word
//!   `kubulukira` stacks THREE derivational suffixes, REV + separado + APPLIC, which depth 2
//!   silently loses). Depth = rule count is the engine-faithful bound for the default
//!   `multipleApplication = 1` case (each rule can apply once, so no chain exceeds the rule
//!   count); a rule with `max_apps > 1` could still exceed it — none exists in the reference
//!   grammars, and the corpus recall gate is the empirical backstop. Rules whose first allomorph
//!   classifies `None` (a pure zero morph) are SKIPPED by trie's `rule_op` routing
//!   (`trie.rs:1001-1006` — `MorphOp::None => {}`); this emitter instead includes them in BOTH
//!   layers (an upward deviation; zero such rules exist in Sena — note for future grammars: each
//!   such rule adds an optional epsilon-tag choice per level, so a grammar with many could
//!   inflate candidate counts).
//! - **Outer (post-template) derivation layers** — an addition trie does NOT have, found by the
//!   recall gate: the engine applies later-stratum rules OUTSIDE a completed template (Sena's
//!   stratum-1 `=mbo` clitic lands AFTER the template's final-vowel suffix slot: engine order
//!   `[.., root, IND, ADD]`), while trie places ALL strata's standalone rules in the inner
//!   derivation layer (before suffix slots — order `[.., root, ADD, IND]`, a positional miss).
//!   This emitter wires every template path through `OuterPfx`/`OuterSfx` chains (same rule sets
//!   as the inner layers — a superset of the exact per-stratum split) so both orders exist.
//! - **Bounded compound loop** (`trie.rs::build_compound_loop`, `trie.rs:857-867`): when any
//!   `CompoundingRule` exists, exactly ONE extra root may follow the head root, then control
//!   passes to the suffix derivation layer — same one-extra-root bound as trie.
//!
//! ## Deliberate supersets (upward approximations — the plan's iron rule allows ONLY this
//! direction; a subset is a bug)
//! 1. **Group sharing decouples a template's prefix side from its suffix side.** trie replicates
//!    root wiring per template (cheap epsilon edges into shared root chains — a graph trick lexc
//!    has no equivalent for: a `LEXICON` name is a single forward continuation, so per-template
//!    replication would copy every root line once per template). This emitter groups templates by
//!    their exact `required_syn_fs` `FsId` (9 groups for Sena's 24 templates; identical authored
//!    POS lists collapse to one id in the grammar's own interner) and shares one root section per
//!    group; after the root+derivation section, control joins a UNION of the group's templates'
//!    suffix-slot chains. A word can therefore combine template A's prefix slots with template
//!    B's suffix slots (same category group) — more paths than trie, never fewer.
//! 2. **`derivable_to_category` is approximated one-step and fail-open.** trie's bounded BFS
//!    (`trie.rs:1567-1622`) admits a root to a template if some derivation chain can reach the
//!    template's category. Here: if ANY category-changing standalone rule's `out_syn_fs` unifies
//!    with a group's key, the group admits EVERY root ("permissive") — a strict superset of the
//!    BFS's answer for that group.
//! 3. Bare roots skip the obligatory-inflection gate; root stratum-index-vs-template-stratum
//!    admission (`trie.rs:1105`) is skipped (all roots offered to all groups they categorize
//!    into).
//!
//! ## Tag tape convention
//! Every lexc entry's UPPER side is the morpheme's tag SYMBOL ONLY (never literal underlying
//! text) — `<R:nnnn>`/`<M:nnnn>` (`tags::root_tag_lexc`/`morph_tag_lexc`). The LOWER side is the
//! real surface spelling. This keeps [`tags::decode_path`] a trivial tag-occurrence scan (no
//! literal upper-tape text can ever contain `<`/`>`). The tag for each morpheme sits at the
//! morpheme's SURFACE position — prefix tags precede the root tag, suffix tags follow it —
//! because confirm's `analyses_match` is positional in ascending surface order (plan §2's
//! "positional match trap"; engine order = `allomorphs_in_morph_order`, ascending surface
//! position, `hc-parse/src/morpher.rs:725-746`). Multiple allomorphs of one morpheme are multiple
//! lexc entries sharing ONE tag symbol; free-fluctuating allomorphs are naturally separate
//! entries.
//!
//! ## Surface spelling: boundary characters dropped, representation variants enumerated
//! Sena's affix/root shapes carry literal `Boundary`-kind characters (`+`, the `^0`-family, `.`)
//! that are structural morpheme-juncture markers, NOT real orthography — verified two ways: (a)
//! `hc-parse`'s own generation-output renderer (`surface::to_plain_string`, called with
//! `include_boundaries = false`) strips them from every synthesized word; (b) `hc-hybrid`'s bare
//! walker treats every `Boundary`-kind trie arc as FREE (`walk.rs::is_free_arc` — traversed
//! without consuming input, exactly like an epsilon arc). [`surface_variants`] reproduces this:
//! it re-segments a root/affix's authored text against the surface char-def table (the same
//! greedy longest-match algorithm `hc_grammar::segment::segment` uses) and drops `Boundary`-kind
//! matches.
//!
//! The engine matches SEGMENTS BY CHAR-DEF IDENTITY, not by spelling (`hc_parse::root_trie`'s
//! `edge_matches`; ditto trie.rs's `ArcLabel::Segment { char_def }`): a char-def with several
//! `<Representation>`s (Sena `char4` = {"m", "n"}) matches ANY of its spellings in the input
//! word. A single literal lexc string cannot ("tun", the authored shape of Sena's *mentir*, must
//! also match corpus "tum..." — found as 13 of the first recall gate's 19 misses).
//! [`surface_variants`] therefore returns the CARTESIAN PRODUCT of each matched segment
//! char-def's representations — every spelling the engine would accept. Bounded by
//! [`REP_VARIANT_CAP`]; on overflow the remainder is dropped AND reported as an uncovered item
//! (an explicit, visible under-approximation for a pathological grammar — never triggered by
//! Sena, whose only multi-representation segment char-def is `char4`).
//!
//! ## Normalization
//! [`kept_surface_text`] NFD-normalizes before matching (mirroring `hc_grammar::segment::segment`
//! and, downstream, `hc_parse`'s own `segment_with_features` — the real engine's query words are
//! NFD-matched too). [`crate::analyzer`] NFD-normalizes its own query word the same way before
//! calling `apply_up`, so lexc surface text and query text live in the same normalization space
//! regardless of whether the corpus file itself is NFC or NFD on disk.
//!
//! ## Not emittable as literal lexc (routed to [`EmitReport::uncovered`], never silently dropped)
//! - `RootAllomorphDef::is_pattern` allomorphs (iterative/optional shape nodes — no concrete
//!   spelling).
//! - `OutputAction::Modify`/`InsertContext` ("process morphs" — ablaut/simulfix/class-insertion,
//!   plan §2's "not compilable as strings" citation). Zero uses in Sena; this path is defensive.
//! - Any allomorph whose `classify_affix` role doesn't fit the zone it was reached from (Infix,
//!   Reduplication, Circumfix, Process) — mirrors `trie.rs::append_slots`'s per-allomorph
//!   mismatch check (`trie.rs:941-946`) and `classify_template`'s slot-level uncovered routing
//!   (`trie.rs:884-889`) exactly.
//! - Text that fails to re-segment against the surface table (defensive; the loader already
//!   accepted it once).

use std::collections::BTreeSet;

use hc_featstruct::{is_unifiable, FsId};
use hc_grammar::chardef::{CharDefKind, CharDefTable};
use hc_grammar::model::{
    AffixAllomorphDef, Grammar, MRuleId, MorphRuleDef, MorphemeId, OutputAction, PartRef, SlotDef,
};

use crate::tags;

/// Floor for a derivation layer chain's depth (the actual depth is the rule count routed to that
/// side, but never less than trie's `deriv_depth = 2` — staying >= trie's language is the
/// baseline recall guarantee; see the module doc's derivation-layer section for why rule count,
/// not 2, is the engine-faithful bound).
pub const DERIV_DEPTH_MIN: usize = 2;

/// Cap on the representation-variant cartesian product per emitted morph surface (module doc,
/// "Surface spelling"). Overflow is reported as an uncovered item, never silent.
pub const REP_VARIANT_CAP: usize = 64;

// --- Report types -----------------------------------------------------------------------------

/// One construct this emitter could not represent as literal lexc — never silently dropped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UncoveredItem {
    /// A short machine-stable category: "pattern-allomorph", "process-morph", "unsegmentable-root",
    /// "unsegmentable-affix", "infix", "reduplication", "circumfix-prefix", "circumfix-suffix",
    /// "process".
    pub kind: String,
    /// The rule/entry this was found on (e.g. `"mrule37#allo0"`, `"entry482(morpheme=...)#allo0"`).
    pub id: String,
    pub reason: String,
}

#[derive(Debug, Clone, Default)]
pub struct EmitCounts {
    /// `Grammar::entries.len()` (grammar-wide lexical entry count).
    pub entries: usize,
    /// `Grammar::mrules.len()` (grammar-wide morphological rule count).
    pub rules: usize,
    /// Total `<AffixTemplate><Slot>` count across the grammar (structural, not entry-count).
    pub slots: usize,
    /// Category groups this emitter collapsed the grammar's templates into (superset item 1 in
    /// the module doc). Does not count the template-less section.
    pub groups: usize,
    /// Root/affix allomorph OCCURRENCES that produced at least one lexc entry line (an allomorph
    /// emitted in several slots/levels counts each time — this is an emission-volume number, not
    /// a distinct-allomorph census).
    pub allomorphs_emitted: usize,
    /// Allomorph occurrences routed to `uncovered` instead (pattern shapes, process morphs, zone
    /// mismatches, unsegmentable text) — pre-dedup, same counting convention.
    pub allomorphs_skipped: usize,
    /// Total lexc entry lines written — the number that most directly predicts foma compile cost.
    pub lexc_lines: usize,
}

/// Overall verdict for this grammar's foma path (plan §4, P1 gate F1).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FomaTier {
    /// Every construct the grammar uses was representable (no `uncovered` entries).
    Full,
    /// Emitted successfully but with `uncovered` constructs present (still safe to use — those
    /// constructs simply cannot contribute candidates; nothing was emitted incorrectly).
    Partial { uncovered: usize },
    /// Could not emit a usable network at all (e.g. zero root allomorphs survived); caller should
    /// fall back to the full engine for this grammar entirely.
    Unsupported { reason: String },
}

#[derive(Debug, Clone)]
pub struct EmitReport {
    pub uncovered: Vec<UncoveredItem>,
    pub counts: EmitCounts,
    pub tier: FomaTier,
}

pub struct EmitResult {
    pub lexc_source: String,
    pub report: EmitReport,
}

// --- Affix role classification (ported from hc-hybrid/src/token.rs, no dependency) --------------

/// Mirrors `hc-hybrid/src/token.rs`'s `MorphOp` classification outcome for one allomorph's RHS —
/// ported (not depended-on: `hc-hybrid` is being sunset, plan D8) since only the classification
/// logic is needed, not that crate's packed-token bit scheme (this crate's tags are
/// `MorphemeId`-indexed strings).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
enum Role {
    None,
    Prefix,
    Suffix,
    Infix,
    Reduplication,
    CircumfixPrefix,
    /// Never actually produced by [`classify_affix`] — kept only for enum-discriminant parity
    /// with the original it was ported from (`hc-hybrid/src/token.rs`'s `MorphOp`, whose own
    /// `classify_affix` also only ever returns `CircumfixPrefix` for the leading-AND-trailing
    /// case).
    #[allow(dead_code)]
    CircumfixSuffix,
    Process,
}

impl Role {
    fn label(self) -> &'static str {
        match self {
            Role::None => "none",
            Role::Prefix => "prefix",
            Role::Suffix => "suffix",
            Role::Infix => "infix",
            Role::Reduplication => "reduplication",
            Role::CircumfixPrefix => "circumfix-prefix",
            Role::CircumfixSuffix => "circumfix-suffix",
            Role::Process => "process",
        }
    }
}

/// Port of `hc-hybrid/src/token.rs::classify_affix` (`MorphTokenCodec.ClassifyAffix`,
/// `MorphTokenCodec.cs:76-129`).
fn classify_affix(rhs: &[OutputAction]) -> Role {
    let copy_parts: Vec<PartRef> = rhs
        .iter()
        .filter_map(|a| if let OutputAction::Copy(p) = a { Some(*p) } else { None })
        .collect();
    if copy_parts
        .iter()
        .any(|p| copy_parts.iter().filter(|&&q| q == *p).count() >= 2)
    {
        return Role::Reduplication;
    }

    let mut first_copy: Option<usize> = None;
    let mut last_copy: usize = 0;
    for (i, action) in rhs.iter().enumerate() {
        if matches!(action, OutputAction::Copy(_)) {
            if first_copy.is_none() {
                first_copy = Some(i);
            }
            last_copy = i;
        }
    }

    let Some(first_copy) = first_copy else {
        return if rhs.iter().any(|a| matches!(a, OutputAction::Modify(_, _))) {
            Role::Process
        } else {
            Role::None
        };
    };

    if first_copy < last_copy {
        for action in &rhs[first_copy + 1..last_copy] {
            if !matches!(action, OutputAction::Copy(_)) {
                return Role::Infix;
            }
        }
    }

    let leading_insert = first_copy > 0;
    let trailing_insert = last_copy < rhs.len() - 1;
    if leading_insert && trailing_insert {
        Role::CircumfixPrefix
    } else if leading_insert {
        Role::Prefix
    } else if trailing_insert {
        Role::Suffix
    } else {
        Role::None
    }
}

/// `OutputAction::Modify`/`InsertContext` carry no concrete text (plan §2: "Not compilable as
/// strings"). Checked independently of [`classify_affix`] because a rule's RHS can contain one of
/// these AND still classify as a plain Prefix/Suffix by copy-position alone.
fn has_unemittable_action(rhs: &[OutputAction]) -> bool {
    rhs.iter()
        .any(|a| matches!(a, OutputAction::Modify(_, _) | OutputAction::InsertContext(_)))
}

enum InsertText<'a> {
    /// No `InsertSegments` action at all — a pure zero/null morph (token only, epsilon text).
    None,
    Text(&'a str),
}

/// The first `InsertSegments` action's underlying text (`hc-hybrid/src/trie.rs::first_insert`,
/// text half only — this emitter re-derives kept surface text itself, see [`kept_surface_text`]).
fn first_insert_text(rhs: &[OutputAction]) -> InsertText<'_> {
    for a in rhs {
        if let OutputAction::InsertSegments { shape, .. } = a {
            return InsertText::Text(shape.text.as_str());
        }
    }
    InsertText::None
}

fn owning_morpheme(g: &Grammar, mid: MRuleId) -> MorphemeId {
    match &g.mrules[mid.0 as usize] {
        MorphRuleDef::AffixProcess(def) => def.morpheme,
        MorphRuleDef::Realizational(def) => def.morpheme,
        MorphRuleDef::Compounding(_) => {
            unreachable!("a CompoundingRule id is never routed into an affix emission site")
        }
    }
}

fn allomorphs_of(g: &Grammar, mid: MRuleId) -> &[AffixAllomorphDef] {
    match &g.mrules[mid.0 as usize] {
        MorphRuleDef::AffixProcess(def) => &def.allomorphs,
        MorphRuleDef::Realizational(def) => &def.allomorphs,
        MorphRuleDef::Compounding(_) => &[],
    }
}

/// `trie.rs::required_category`: the requirement FS a rule imposes (empty `FsId(0)` where C#
/// would say null).
fn required_category(g: &Grammar, mid: MRuleId) -> FsId {
    match &g.mrules[mid.0 as usize] {
        MorphRuleDef::AffixProcess(def) => def.required_syn_fs,
        MorphRuleDef::Realizational(def) => def.required_syn_fs,
        MorphRuleDef::Compounding(_) => FsId(0),
    }
}

/// `trie.rs::rule_op`: a rule's primary role, from its FIRST allomorph.
fn rule_role(g: &Grammar, mid: MRuleId) -> Role {
    allomorphs_of(g, mid)
        .first()
        .map(|a| classify_affix(&a.rhs))
        .unwrap_or(Role::None)
}

// --- Surface text (boundary-stripped, as-authored) ----------------------------------------------

fn surface_table(g: &Grammar) -> &CharDefTable {
    let surface_stratum = g
        .strata
        .last()
        .expect("a loaded grammar always has at least one stratum");
    &g.char_tables[surface_stratum.table.0 as usize]
}

/// Every surface spelling the engine would accept for `text` (module doc, "Surface spelling"):
/// re-run `hc_grammar::segment::segment`'s greedy longest-match algorithm, drop `Boundary`-kind
/// matches, and take the cartesian product of each `Segment`-kind match's char-def
/// REPRESENTATIONS (the engine matches segments by char-def identity, so any representation of
/// the matched char-def is accepted in the input word — Sena `char4` = {"m","n"}).
///
/// Returns `(variants, overflowed)`: `variants` deduped, capped at [`REP_VARIANT_CAP`];
/// `overflowed = true` means spellings were dropped (the caller must report it — an explicit
/// under-approximation, never silent). `None` if some position fails to match any char-def
/// (defensive; the loader already accepted this text once).
fn surface_variants(table: &CharDefTable, text: &str) -> Option<(Vec<String>, bool)> {
    let normalized = hc_grammar::nfd::nfd(text);
    let chars: Vec<char> = normalized.chars().collect();
    let mut variants: Vec<String> = vec![String::new()];
    let mut overflowed = false;
    let mut i = 0usize;
    while i < chars.len() {
        let mut matched = false;
        for j in (1..=(chars.len() - i)).rev() {
            let candidate: String = chars[i..i + j].iter().collect();
            if let Some(cd_id) = table.lookup_nfd(&candidate) {
                let cd = table.get(cd_id);
                if cd.kind() == CharDefKind::Segment {
                    let reps = cd.representations_nfd();
                    if reps.len() <= 1 {
                        // Common case: append in place, no reallocation of the variant set.
                        for v in &mut variants {
                            v.push_str(&candidate);
                        }
                    } else {
                        let mut next =
                            Vec::with_capacity(variants.len().saturating_mul(reps.len()));
                        'grow: for v in &variants {
                            for rep in reps {
                                if next.len() >= REP_VARIANT_CAP {
                                    overflowed = true;
                                    break 'grow;
                                }
                                let mut nv = v.clone();
                                nv.push_str(rep);
                                next.push(nv);
                            }
                        }
                        variants = next;
                    }
                }
                i += j;
                matched = true;
                break;
            }
        }
        if !matched {
            return None;
        }
    }
    variants.sort_unstable();
    variants.dedup();
    Some((variants, overflowed))
}

/// Escape lexc's special characters in literal (non-tag) text: `%` (lexc's own escape char), `<`/
/// `:`/`>` (XRE-block/pair-separator/C-foma-NONRESERVED syntax), and `0` (lexc's bare-zero
/// alignment-epsilon marker — gate F0's finding, `tests/f0_viability.rs`'s module doc: this
/// applies to ANY text, not just tag numerals). `;`, `!`, and space can't normally survive
/// [`kept_surface_text`] (they'd fail char-def lookup first), but escaping them is cheap
/// insurance.
fn escape_lexc_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(c, '%' | '<' | '>' | ':' | '0' | ';' | '!' | ' ') {
            out.push('%');
        }
        out.push(c);
    }
    out
}

// --- lexc source writing helpers -----------------------------------------------------------------

fn write_lexicon_header(out: &mut String, name: &str) {
    out.push_str("\nLEXICON ");
    out.push_str(name);
    out.push('\n');
}

/// A bare continuation-only line (standard lexc idiom for a pure structural redirect — no symbols
/// consumed on either tape).
fn write_bare(out: &mut String, continuation: &str, counts: &mut EmitCounts) {
    out.push_str(continuation);
    out.push_str(" ;\n");
    counts.lexc_lines += 1;
}

/// One tagged entry: upper = the tag symbol ONLY (module doc's tag-tape convention), lower = the
/// (already boundary-stripped) surface text, escaped. Empty surface = lexc's `0` epsilon.
fn write_tag_entry(
    out: &mut String,
    tag_lexc: &str,
    surface: &str,
    continuation: &str,
    counts: &mut EmitCounts,
) {
    let escaped = escape_lexc_text(surface);
    out.push_str(tag_lexc);
    out.push(':');
    if escaped.is_empty() {
        out.push('0');
    } else {
        out.push_str(&escaped);
    }
    out.push(' ');
    out.push_str(continuation);
    out.push_str(" ;\n");
    counts.lexc_lines += 1;
}

// --- Root collection ------------------------------------------------------------------------------

struct RootRec {
    morpheme: MorphemeId,
    category: FsId,
    /// Every accepted spelling ([`surface_variants`]), each emitted as its own lexc entry line
    /// sharing this morpheme's one tag symbol.
    variants: Vec<String>,
}

fn collect_roots(
    g: &Grammar,
    table: &CharDefTable,
    uncovered: &mut Vec<UncoveredItem>,
    counts: &mut EmitCounts,
) -> Vec<RootRec> {
    let mut roots = Vec::new();
    // Stratum order then entry order, mirroring trie.rs's own roots collection (`run()`,
    // trie.rs:966-981) — deterministic Vec walks only.
    for sd in &g.strata {
        for &entry_id in &sd.entries {
            let entry = &g.entries[entry_id.0 as usize];
            let morpheme_name = g
                .morphemes
                .get(entry.morpheme.0 as usize)
                .map(|m| m.xml_key.as_str())
                .unwrap_or("?");
            for (allo_idx, allo) in entry.allomorphs.iter().enumerate() {
                let label = format!(
                    "entry{}(morpheme={morpheme_name})#allo{allo_idx}",
                    entry_id.0
                );
                if allo.is_pattern {
                    uncovered.push(UncoveredItem {
                        kind: "pattern-allomorph".to_string(),
                        id: label,
                        reason: "root allomorph shape has iterative/optional nodes (a lexical PATTERN); no concrete spelling to emit (v1)".to_string(),
                    });
                    counts.allomorphs_skipped += 1;
                    continue;
                }
                match surface_variants(table, &allo.shape.text) {
                    Some((variants, overflowed)) => {
                        if overflowed {
                            uncovered.push(UncoveredItem {
                                kind: "rep-variant-overflow".to_string(),
                                id: label.clone(),
                                reason: format!(
                                    "root shape {:?} exceeds {REP_VARIANT_CAP} representation variants; excess spellings dropped",
                                    allo.shape.text
                                ),
                            });
                        }
                        roots.push(RootRec {
                            morpheme: entry.morpheme,
                            category: entry.syn_fs,
                            variants,
                        });
                        counts.allomorphs_emitted += 1;
                    }
                    None => {
                        uncovered.push(UncoveredItem {
                            kind: "unsegmentable-root".to_string(),
                            id: label,
                            reason: format!(
                                "root shape {:?} does not re-segment against the surface char-def table",
                                allo.shape.text
                            ),
                        });
                        counts.allomorphs_skipped += 1;
                    }
                }
            }
        }
    }
    roots
}

// --- Affix entry emission (shared by slot chains and derivation layers) ---------------------------

/// Emit every emittable allomorph of `mid` as one tagged lexc entry with continuation `next`,
/// requiring each allomorph's role to be `zone_role` (or `None` — a zero morph is legal in either
/// zone, exactly like `trie.rs::append_slots`'s `aop != op && aop != MorphOp::None` check,
/// trie.rs:941-946).
#[allow(clippy::too_many_arguments)]
fn emit_rule_allomorphs(
    out: &mut String,
    g: &Grammar,
    table: &CharDefTable,
    mid: MRuleId,
    zone_role: Role,
    width: usize,
    next: &str,
    uncovered: &mut Vec<UncoveredItem>,
    counts: &mut EmitCounts,
) {
    let morpheme = owning_morpheme(g, mid);
    let tag_lexc = tags::morph_tag_lexc(morpheme, width);
    for (allo_idx, allo) in allomorphs_of(g, mid).iter().enumerate() {
        let label = format!("mrule{}#allo{allo_idx}", mid.0);
        if has_unemittable_action(&allo.rhs) {
            uncovered.push(UncoveredItem {
                kind: "process-morph".to_string(),
                id: label,
                reason: "Modify/InsertContext action has no literal text to emit (v1)".to_string(),
            });
            counts.allomorphs_skipped += 1;
            continue;
        }
        let role = classify_affix(&allo.rhs);
        if role != zone_role && role != Role::None {
            uncovered.push(UncoveredItem {
                kind: role.label().to_string(),
                id: label,
                reason: format!(
                    "allomorph classifies as {role:?} but its rule is referenced in a {zone_role:?} position"
                ),
            });
            counts.allomorphs_skipped += 1;
            continue;
        }
        match first_insert_text(&allo.rhs) {
            InsertText::None => {
                write_tag_entry(out, &tag_lexc, "", next, counts);
                counts.allomorphs_emitted += 1;
            }
            InsertText::Text(t) => match surface_variants(table, t) {
                Some((variants, overflowed)) => {
                    if overflowed {
                        uncovered.push(UncoveredItem {
                            kind: "rep-variant-overflow".to_string(),
                            id: label.clone(),
                            reason: format!(
                                "affix insert text {t:?} exceeds {REP_VARIANT_CAP} representation variants; excess spellings dropped"
                            ),
                        });
                    }
                    for surface in &variants {
                        write_tag_entry(out, &tag_lexc, surface, next, counts);
                    }
                    counts.allomorphs_emitted += 1;
                }
                None => {
                    uncovered.push(UncoveredItem {
                        kind: "unsegmentable-affix".to_string(),
                        id: label,
                        reason: format!(
                            "affix insert text {t:?} does not re-segment against the surface char-def table"
                        ),
                    });
                    counts.allomorphs_skipped += 1;
                }
            },
        }
    }
}

// --- Derivation layer chain (trie.rs::build_derivation_layer) -------------------------------------

/// Emit a chain of optional derivation layers named `{prefix}0` .. `{prefix}{depth-1}`, each
/// offering every rule in `rules` once, ending at `exit`. Depth = `rules.len()` floored at
/// [`DERIV_DEPTH_MIN`] (module doc: the engine-faithful bound for `multipleApplication = 1` —
/// each rule can apply at most once, so no derivation chain is longer than the rule count).
/// Mirrors `trie.rs::build_derivation_layer` (each level: an epsilon skip to the next level plus
/// one token+arc path per rule allomorph). Always defines `{prefix}0`, even when `rules` is
/// empty (a plain passthrough), so callers can reference it unconditionally.
#[allow(clippy::too_many_arguments)]
fn build_deriv_chain(
    out: &mut String,
    g: &Grammar,
    table: &CharDefTable,
    prefix: &str,
    zone_role: Role,
    rules: &[MRuleId],
    width: usize,
    exit: &str,
    uncovered: &mut Vec<UncoveredItem>,
    counts: &mut EmitCounts,
) -> String {
    let entry_name = format!("{prefix}0");
    if rules.is_empty() {
        write_lexicon_header(out, &entry_name);
        write_bare(out, exit, counts);
        return entry_name;
    }
    let depth = rules.len().max(DERIV_DEPTH_MIN);
    for level in 0..depth {
        let name = format!("{prefix}{level}");
        write_lexicon_header(out, &name);
        let next = if level + 1 == depth {
            exit.to_string()
        } else {
            format!("{prefix}{}", level + 1)
        };
        // The whole level is optional (trie: `add_epsilon(current, after)` before the per-rule
        // arcs, trie.rs:807-808).
        write_bare(out, &next, counts);
        for &mid in rules {
            emit_rule_allomorphs(
                out, g, table, mid, zone_role, width, &next, uncovered, counts,
            );
        }
    }
    entry_name
}

// --- Slot chains (trie.rs::classify_template + append_slots) --------------------------------------

/// `trie.rs::slot_op` (C# `SlotOp`, `FstTemplateAnalyzer.cs:1238-1254`): a slot's zone is that of
/// its first Prefix/Suffix-classified rule; a slot with only zero-morph rules counts as Suffix.
fn slot_role(g: &Grammar, slot: &SlotDef) -> Role {
    let mut has_zero = false;
    for &mid in &slot.rules {
        let role = rule_role(g, mid);
        if role == Role::Prefix || role == Role::Suffix {
            return role;
        }
        if role == Role::None {
            has_zero = true;
        }
    }
    if has_zero {
        Role::Suffix
    } else {
        Role::None
    }
}

/// `trie.rs::classify_template`: split a template's slots into prefix (REVERSED to surface order)
/// and suffix lists, routing any exotic-op slot rule to `uncovered`.
fn classify_template<'g>(
    g: &'g Grammar,
    template: &'g hc_grammar::model::AffixTemplateDef,
    uncovered: &mut Vec<UncoveredItem>,
) -> (Vec<&'g SlotDef>, Vec<&'g SlotDef>) {
    let mut prefix = Vec::new();
    let mut suffix = Vec::new();
    for slot in &template.slots {
        match slot_role(g, slot) {
            Role::Prefix => prefix.push(slot),
            Role::Suffix => suffix.push(slot),
            _ => {
                for &mid in &slot.rules {
                    let role = rule_role(g, mid);
                    if role != Role::Prefix && role != Role::Suffix && role != Role::None {
                        uncovered.push(UncoveredItem {
                            kind: role.label().to_string(),
                            id: format!("mrule{}", mid.0),
                            reason: format!(
                                "template slot rule's primary allomorph classifies as {role:?}; slot dropped (v1, mirrors trie.rs classify_template)"
                            ),
                        });
                    }
                }
            }
        }
    }
    prefix.reverse();
    (prefix, suffix)
}

/// `trie.rs::append_slots`: emit one lexicon per slot, in order, each offering every (unifiable,
/// zone-fitting) rule allomorph once; optional slots add an epsilon skip. Chain is named
/// `{prefix}0` .. and ends at `exit`; always defines `{prefix}0` (passthrough when `slots` is
/// empty).
#[allow(clippy::too_many_arguments)]
fn build_slot_chain(
    out: &mut String,
    g: &Grammar,
    table: &CharDefTable,
    prefix: &str,
    slots: &[&SlotDef],
    zone_role: Role,
    template_category: FsId,
    width: usize,
    exit: &str,
    uncovered: &mut Vec<UncoveredItem>,
    counts: &mut EmitCounts,
) -> String {
    let entry_name = format!("{prefix}0");
    if slots.is_empty() {
        write_lexicon_header(out, &entry_name);
        write_bare(out, exit, counts);
        return entry_name;
    }
    for (si, slot) in slots.iter().enumerate() {
        let name = format!("{prefix}{si}");
        write_lexicon_header(out, &name);
        let next = if si + 1 == slots.len() {
            exit.to_string()
        } else {
            format!("{prefix}{}", si + 1)
        };
        if slot.optional {
            write_bare(out, &next, counts);
        }
        for &mid in &slot.rules {
            // trie.rs::append_slots's rule-level category gate (trie.rs:933-939): skip a slot
            // rule whose own requirement can't unify with the template's category.
            let req = required_category(g, mid);
            let req_fs = g.fs_interner.get(req);
            if !req_fs.is_empty() {
                let tmpl_fs = g.fs_interner.get(template_category);
                if !is_unifiable(tmpl_fs, req_fs) {
                    continue;
                }
            }
            emit_rule_allomorphs(
                out, g, table, mid, zone_role, width, &next, uncovered, counts,
            );
        }
    }
    entry_name
}

// --- Top-level emit ---------------------------------------------------------------------------

pub fn emit(g: &Grammar) -> EmitResult {
    let width = tags::tag_width(g.morphemes.len());
    let table = surface_table(g);

    let mut uncovered: Vec<UncoveredItem> = Vec::new();
    let mut counts = EmitCounts {
        entries: g.entries.len(),
        rules: g.mrules.len(),
        ..Default::default()
    };

    let roots = collect_roots(g, table, &mut uncovered, &mut counts);

    // Standalone (stratum-attached) derivation rules, classified by primary role — mirrors
    // trie.rs run()'s "Standalone derivational affix rules" loop (`trie.rs:993-1008`), except
    // Role::None rules are INCLUDED in both zones rather than skipped (module doc, upward
    // deviation; trie's `MorphOp::None => {}` silently drops them).
    let mut deriv_prefix: Vec<MRuleId> = Vec::new();
    let mut deriv_suffix: Vec<MRuleId> = Vec::new();
    let mut has_compounding_rules = false;
    let mut category_changing_out: Vec<FsId> = Vec::new();
    for sd in &g.strata {
        for &mid in &sd.mrules {
            match &g.mrules[mid.0 as usize] {
                MorphRuleDef::Compounding(_) => {
                    has_compounding_rules = true;
                    continue;
                }
                MorphRuleDef::AffixProcess(def) => {
                    if !g.fs_interner.get(def.out_syn_fs).is_empty() {
                        category_changing_out.push(def.out_syn_fs);
                    }
                }
                MorphRuleDef::Realizational(_) => {}
            }
            match rule_role(g, mid) {
                Role::Prefix => deriv_prefix.push(mid),
                Role::Suffix => deriv_suffix.push(mid),
                Role::None => {
                    deriv_prefix.push(mid);
                    deriv_suffix.push(mid);
                }
                other => uncovered.push(UncoveredItem {
                    kind: other.label().to_string(),
                    id: format!("mrule{}", mid.0),
                    reason: format!(
                        "standalone rule's primary allomorph classifies as {other:?}; not representable (v1)"
                    ),
                }),
            }
        }
    }

    // Template groups: one per distinct `required_syn_fs`, first-seen template document order.
    let mut group_keys: Vec<FsId> = Vec::new();
    let mut group_templates: Vec<Vec<usize>> = Vec::new();
    for (ti, t) in g.templates.iter().enumerate() {
        counts.slots += t.slots.len();
        match group_keys.iter().position(|&k| k == t.required_syn_fs) {
            Some(gi) => group_templates[gi].push(ti),
            None => {
                group_keys.push(t.required_syn_fs);
                group_templates.push(vec![ti]);
            }
        }
    }
    counts.groups = group_keys.len();

    // Permissive groups: fail-open stand-in for trie's derivable_to_category BFS (module doc
    // superset item 2).
    let permissive: Vec<bool> = group_keys
        .iter()
        .map(|&key| {
            let key_fs = g.fs_interner.get(key);
            category_changing_out
                .iter()
                .any(|&ocat| is_unifiable(g.fs_interner.get(ocat), key_fs))
        })
        .collect();

    if roots.is_empty() {
        let report = EmitReport {
            uncovered,
            counts,
            tier: FomaTier::Unsupported {
                reason: "no root allomorph in this grammar produced any literal lexc text"
                    .to_string(),
            },
        };
        return EmitResult {
            lexc_source: String::new(),
            report,
        };
    }

    let has_template_less_section =
        !deriv_prefix.is_empty() || !deriv_suffix.is_empty() || has_compounding_rules;

    let mut out = String::new();

    // Multichar_Symbols: every root morpheme + every rule morpheme reachable from any emission
    // site (deriv layers + template slots). Declaring a symbol that ends up unused is harmless.
    let mut symbols: BTreeSet<(bool, u32)> = BTreeSet::new();
    for r in &roots {
        symbols.insert((true, r.morpheme.0));
    }
    for &mid in deriv_prefix.iter().chain(deriv_suffix.iter()) {
        symbols.insert((false, owning_morpheme(g, mid).0));
    }
    for t in &g.templates {
        for slot in &t.slots {
            for &mid in &slot.rules {
                if !matches!(g.mrules[mid.0 as usize], MorphRuleDef::Compounding(_)) {
                    symbols.insert((false, owning_morpheme(g, mid).0));
                }
            }
        }
    }
    out.push_str("Multichar_Symbols\n");
    for &(is_root, id) in &symbols {
        let lexc = if is_root {
            tags::root_tag_lexc(MorphemeId(id), width)
        } else {
            tags::morph_tag_lexc(MorphemeId(id), width)
        };
        out.push_str(&lexc);
        out.push('\n');
    }

    // One lexc entry line per accepted spelling of one root (module doc, "Surface spelling").
    let write_root_entries =
        |out: &mut String, roots: &[&RootRec], continuation: &str, counts: &mut EmitCounts| {
            for r in roots {
                let tag_lexc = tags::root_tag_lexc(r.morpheme, width);
                for v in &r.variants {
                    write_tag_entry(out, &tag_lexc, v, continuation, counts);
                }
            }
        };
    let all_roots: Vec<&RootRec> = roots.iter().collect();
    let has_templates = !g.templates.is_empty();

    // ---- LEXICON Root: bare roots, the template-less section, the outer-prefix hop into the
    // per-template dispatch ----
    write_lexicon_header(&mut out, "Root");
    write_root_entries(&mut out, &all_roots, "#", &mut counts);
    if has_template_less_section {
        write_bare(&mut out, "TLPfx0", &mut counts);
    }
    if has_templates {
        // Template paths go through the OUTER prefix derivation layer first (module doc,
        // "Outer (post-template) derivation layers") and then the per-template dispatch.
        write_bare(&mut out, "OuterPfx0", &mut counts);
    }

    if has_templates {
        build_deriv_chain(
            &mut out, g, table, "OuterPfx", Role::Prefix, &deriv_prefix, width, "TmplDispatch",
            &mut uncovered, &mut counts,
        );
        // One line per template's prefix-chain entry, deduped (templates with no prefix slots
        // all point straight at their group's prefix-derivation entry). `classify_template` here
        // is only probing prefix-emptiness; its uncovered routing happens once, on the real
        // emission pass below (a throwaway Vec avoids double-reporting).
        write_lexicon_header(&mut out, "TmplDispatch");
        let mut dispatch_lines: BTreeSet<String> = BTreeSet::new();
        for (gi, tis) in group_templates.iter().enumerate() {
            for &ti in tis {
                let (prefix_slots, _) = classify_template(g, &g.templates[ti], &mut Vec::new());
                if prefix_slots.is_empty() {
                    dispatch_lines.insert(format!("G{gi}PfxD0"));
                } else {
                    dispatch_lines.insert(format!("T{ti}P0"));
                }
            }
        }
        for line in &dispatch_lines {
            write_bare(&mut out, line, &mut counts);
        }
        // The OUTER suffix derivation layer every template's suffix side exits through (engine:
        // later-stratum rules apply outside a completed template — see module doc).
        build_deriv_chain(
            &mut out, g, table, "OuterSfx", Role::Suffix, &deriv_suffix, width, "#",
            &mut uncovered, &mut counts,
        );
    }

    // ---- Template-less derivation section (trie.rs:1035-1063) ----
    if has_template_less_section {
        build_deriv_chain(
            &mut out, g, table, "TLPfx", Role::Prefix, &deriv_prefix, width, "TLRoots",
            &mut uncovered, &mut counts,
        );
        write_lexicon_header(&mut out, "TLRoots");
        write_root_entries(&mut out, &all_roots, "TLPost", &mut counts);
        write_lexicon_header(&mut out, "TLPost");
        write_bare(&mut out, "TLSfx0", &mut counts);
        if has_compounding_rules {
            write_bare(&mut out, "TLCmp", &mut counts);
            write_lexicon_header(&mut out, "TLCmp");
            write_root_entries(&mut out, &all_roots, "TLSfx0", &mut counts);
        }
        build_deriv_chain(
            &mut out, g, table, "TLSfx", Role::Suffix, &deriv_suffix, width, "#",
            &mut uncovered, &mut counts,
        );
    }

    // ---- Per-group root sections + per-template slot chains ----
    for (gi, &key) in group_keys.iter().enumerate() {
        // Per-template suffix chains, then the group's suffix join, suffix derivation layers,
        // compound hop, roots, prefix derivation layers, and each template's prefix chain.
        let mut join_lines: BTreeSet<String> = BTreeSet::new();
        for &ti in &group_templates[gi] {
            let template = &g.templates[ti];
            let (_, suffix_slots) = classify_template(g, template, &mut uncovered);
            if suffix_slots.is_empty() {
                join_lines.insert("OuterSfx0".to_string());
            } else {
                let entry = build_slot_chain(
                    &mut out,
                    g,
                    table,
                    &format!("T{ti}Z"),
                    &suffix_slots,
                    Role::Suffix,
                    template.required_syn_fs,
                    width,
                    "OuterSfx0",
                    &mut uncovered,
                    &mut counts,
                );
                join_lines.insert(entry);
            }
        }
        let join_name = format!("G{gi}Join");
        write_lexicon_header(&mut out, &join_name);
        for line in &join_lines {
            write_bare(&mut out, line, &mut counts);
        }

        let sfx_deriv_entry = build_deriv_chain(
            &mut out,
            g,
            table,
            &format!("G{gi}SfxD"),
            Role::Suffix,
            &deriv_suffix,
            width,
            &join_name,
            &mut uncovered,
            &mut counts,
        );

        let post_name = format!("G{gi}Post");
        write_lexicon_header(&mut out, &post_name);
        write_bare(&mut out, &sfx_deriv_entry, &mut counts);
        if has_compounding_rules {
            let cmp_name = format!("G{gi}Cmp");
            write_bare(&mut out, &cmp_name, &mut counts);
            write_lexicon_header(&mut out, &cmp_name);
            write_root_entries(&mut out, &all_roots, &sfx_deriv_entry, &mut counts);
        }

        let roots_name = format!("G{gi}Roots");
        write_lexicon_header(&mut out, &roots_name);
        let key_fs = g.fs_interner.get(key);
        let eligible_roots: Vec<&RootRec> = roots
            .iter()
            .filter(|r| {
                permissive[gi]
                    || key_fs.is_empty()
                    || is_unifiable(g.fs_interner.get(r.category), key_fs)
            })
            .collect();
        if eligible_roots.is_empty() {
            // Keep the lexicon non-empty (defensive — a group whose category no root can ever
            // satisfy; the passthrough admits a root-less path, harmless overgeneration).
            write_bare(&mut out, &post_name, &mut counts);
        } else {
            write_root_entries(&mut out, &eligible_roots, &post_name, &mut counts);
        }

        build_deriv_chain(
            &mut out,
            g,
            table,
            &format!("G{gi}PfxD"),
            Role::Prefix,
            &deriv_prefix,
            width,
            &roots_name,
            &mut uncovered,
            &mut counts,
        );

        for &ti in &group_templates[gi] {
            let template = &g.templates[ti];
            let (prefix_slots, _) = classify_template(g, template, &mut Vec::new());
            if prefix_slots.is_empty() {
                continue; // LEXICON Root already points straight at G{gi}PfxD0.
            }
            build_slot_chain(
                &mut out,
                g,
                table,
                &format!("T{ti}P"),
                &prefix_slots,
                Role::Prefix,
                template.required_syn_fs,
                width,
                &format!("G{gi}PfxD0"),
                &mut uncovered,
                &mut counts,
            );
        }
    }

    // Dedup uncovered reports (the same rule/allomorph can be visited from multiple slots/
    // groups/levels).
    let mut seen_uncovered: BTreeSet<(String, String, String)> = BTreeSet::new();
    uncovered.retain(|u| seen_uncovered.insert((u.kind.clone(), u.id.clone(), u.reason.clone())));

    let tier = if uncovered.is_empty() {
        FomaTier::Full
    } else {
        FomaTier::Partial {
            uncovered: uncovered.len(),
        }
    };

    EmitResult {
        lexc_source: out,
        report: EmitReport {
            uncovered,
            counts,
            tier,
        },
    }
}
