//! F3 gate (HYBRID_FST_RUST_PLAN.md §8): "`StateCount` equal per grammar to the (regenerated, not
//! doc-quoted) golden ... the new structural dump byte-identical on ALL THREE grammars".
//!
//! Builds the trie from a live grammar + fresh `SurfacePhonology`/`Morpher` (mirroring C#'s
//! `FstTemplateAnalyzer(language, morpher)` two-arg ctor: junction probing ON, default
//! `maxStates`/`derivDepth`), reads `{grammar}/stats.txt`'s `== StateCount ==` line and
//! `{grammar}/structural-dump.txt` (both regenerated by this milestone's C# `FstStructuralDump`
//! extension, `fst-oracle` branch), and asserts byte-identical equality — the mechanical half of
//! the F3 gate (§8: "Sena's dump will be large ... the diff should still be mechanical").

use std::path::{Path, PathBuf};

use hc_hybrid::canon::structural_dump;
use hc_hybrid::surface::SurfacePhonology;
use hc_hybrid::trie::Trie;
use hc_parse::Morpher;

fn sample_path(name: &str) -> Option<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let path = manifest_dir.join("../../../samples/data").join(name);
    path.exists().then_some(path)
}

fn golden_dir(grammar: &str) -> Option<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let path = manifest_dir
        .join("../../parity-out/golden/fst-advisor")
        .join(grammar);
    path.is_dir().then_some(path)
}

/// The `== StateCount ==` section is just the next non-empty line after the header (a single
/// integer) -- same section-extraction convention as `f2_surface_phonology_gate.rs`.
fn golden_state_count(stats_text: &str) -> usize {
    let mut lines = stats_text.lines().map(|l| l.trim_end_matches('\r'));
    for line in lines.by_ref() {
        if line == "== StateCount ==" {
            break;
        }
    }
    lines
        .next()
        .expect("StateCount value line")
        .trim()
        .parse()
        .expect("StateCount is an integer")
}

fn run_gate(grammar_file: &str, golden_dir_name: &str) {
    let Some(gpath) = sample_path(grammar_file) else {
        eprintln!("skipping {grammar_file}: not present on disk");
        return;
    };
    let Some(gdir) = golden_dir(golden_dir_name) else {
        eprintln!("skipping {golden_dir_name}: golden dir not present on disk");
        return;
    };
    let stats_path = gdir.join("stats.txt");
    let dump_path = gdir.join("structural-dump.txt");
    if !stats_path.exists() || !dump_path.exists() {
        eprintln!("skipping {golden_dir_name}: stats.txt/structural-dump.txt not present (regenerate via fst-oracle's fst-stats)");
        return;
    }

    let xml = std::fs::read_to_string(&gpath).expect("read grammar");
    let g = hc_grammar::load(&xml).unwrap_or_else(|e| panic!("failed to load grammar: {e}"));
    let morpher = Morpher::new(&g, usize::MAX);
    let surface = SurfacePhonology::new(&g);

    // Mirrors C#'s `FstTemplateAnalyzer(language, morpher)` two-arg ctor defaults exactly:
    // maxStates=1_000_000, derivDepth=2, enableJunctionProbing=true, maxBeamWork unused here (F4).
    let trie = Trie::build(&g, &surface, &morpher, 1_000_000, 2, true);

    let stats_text = std::fs::read_to_string(&stats_path).expect("read stats.txt golden");
    let expected_state_count = golden_state_count(&stats_text);
    assert_eq!(
        trie.state_count(),
        expected_state_count,
        "{golden_dir_name}: StateCount mismatch (golden {expected_state_count}, got {})",
        trie.state_count()
    );

    let golden_dump_text =
        std::fs::read_to_string(&dump_path).expect("read structural-dump.txt golden");
    let golden_lines: Vec<&str> = golden_dump_text
        .lines()
        .map(|l| l.trim_end_matches('\r'))
        .collect();
    let rust_lines = structural_dump(&g, &trie);

    assert_eq!(
        rust_lines.len(),
        golden_lines.len(),
        "{golden_dir_name}: structural dump line-count mismatch (golden {}, got {})",
        golden_lines.len(),
        rust_lines.len()
    );
    // Line-by-line rather than a single big `assert_eq!` on the whole `Vec`: a mismatch report on
    // an 18,871-state Sena dump is unreadable as one diff; report the first divergent line index.
    for (i, (rust_line, golden_line)) in rust_lines.iter().zip(golden_lines.iter()).enumerate() {
        assert_eq!(
            rust_line, golden_line,
            "{golden_dir_name}: structural dump diverges at sorted line {i}"
        );
    }
}

#[test]
fn indonesian_trie_matches_golden_state_count_and_structural_dump() {
    run_gate("indonesian-hc.xml", "indonesian");
}

#[test]
fn sena_trie_matches_golden_state_count_and_structural_dump() {
    run_gate("sena-hc.xml", "sena");
}

/// Amharic's junction probing is expensive (§8.3: ~112s in C#, ~104s Rust-release per the F2
/// gate's own `#[ignore]`) -- same discipline as `f2_surface_phonology_gate.rs`'s Amharic test:
/// ignored by default, run explicitly with `--ignored --release` once the golden exists.
#[test]
#[ignore = "slow probe: Amharic's 417-segment alphabet makes DeletionJunctions probing expensive \
            in debug builds -- same cost as the F2 gate's ignored Amharic test. Run with \
            --ignored --release."]
fn amharic_trie_matches_golden_state_count_and_structural_dump() {
    run_gate("amharic-hc.xml", "amharic");
}
